RedRoverSchool/JenkinsQA_05

src/test/java/javanisty/DmitryTest.java
Created package our group and i created first test (how teamlead this group) in this package
=> Add first test in group javanisty

src/test/java/JavanistyTest.java, src/test/java/javanisty/DmitryTest.java
Исправил свою ошибку, удалил папку с названием группы, переименовал файл в название группы и перенес 
в JenkinsQA_05/src/test/java/
=> Update after add first test group javanisty

src/test/java/GroupSqaeTest.java
=> Added tests for Magazine

src/test/java/IrynaOkunFirstTest.java
=> irynaOkunFirstTestAdd

src/test/java/SpiritMastersTest.java
=> SpiritMastersTest | testHerokuapp_gdiksanov

src/test/java/SpiritMastersTest.java
Added test checkButtonsLink_AFedorova_Test
=> SpiritMastersTest | checkButtonsLink_AFedorova_Test

src/test/java/GroupObukhovTest.java
=> add testLinkContractJoin

src/test/java/GroupObukhov.java, src/test/java/JavanistyTest.java, src/test/java/SpiritMastersTest.java
Adedd testFillRegistrationForm_OlPolezhaeva();
=> SpiritMastersTest | testFillRegistrationForm_OlPolezhaeva()

src/test/java/SpiritMastersTest.java
added test redirect to new page 
moved the private method to the top of the class
=> SpiritMastersTest | added testRedirectToSeleniumTrainingTab()

src/test/java/GroupTeamRocketTest.java
=> added test TermsAndConditions

src/test/java/GroupObukhovTest.java, src/test/java/SpiritMastersTest.java
add testCheckBrandBookBasicColorsHEX and testCheckBrandBookAdditionalColorsHEX
=> add two tests

src/test/java/CleanCodeTest.java
=> AV new test

src/test/java/GroupDreamTeamTest.java, src/test/java/GroupSqaeTest.java
I added new test to GreamTeam class
=> Added new test by Darina

src/test/java/SpiritMastersTest.java
=> SpiritMastersTest | testDSFindTitle()

src/test/java/SpiritMastersTest.java
added testCheckButtonTutotials_LPlucci() to SpiritMastersTest
=> SpiritMastersTest | testCheckButtonTutotials_LPlucci()

src/test/java/GroupTeamRocketTest.java
added testBrowseLanguages_NO, changed testFindTitleGuide_NataliiaOliver
=> added testBrowseLanguages_NO, changed testFindTitleGuide_NataliiaOliver

src/test/java/SpiritMastersTest.java
Added test testTextBoxFields_AFedorova()
Updated name for test testCheckButtonLink_AFedorova()
=> SpiritMastersTest | Added testTextBoxFields_AFedorova()

src/test/java/GroupSqaeTest.java, src/test/java/GroupTeamRocketTest.java
One test refactored as it'd been tagged @Ignore. Another test has been added to the class.
=> One test refactored. Another one has been added.

src/test/java/RustamKhRedCodeTest.java
add method auto filling information  on site https://formy-project.herokuapp.com
testAutoCompleteFieldsWebForm()
=> First test

src/test/java/SpiritMastersTest.java
Added testCheckBoxes_AFedorova()
=> SpiritMastersTest | testCheckBoxes_AFedorova()

src/test/java/CleanCodeTest.java
add testPageSales for CleanCode
=> add testPageSales

src/test/java/SpiritMastersTest.java
SpiritMastersTest | added testOpenweathermap_justGoToGuide_gdiksanov()
=> SpiritMastersTest | added testOpenweathermap_justGoToGuide_gdiksanov()

src/test/java/CleanCodeTest.java
=> add testTextContactsIsPresent

src/test/java/KarinaTests.java
test with login page was prepared
=> test with login page was prepared

src/test/java/SpiritMastersTest.java, src/test/java/WondMindsTest.java
=> Happy straw/new test

src/test/java/MykhailoTest.java
=> My first test commit

src/test/java/GroupDonSimonTutankhamonTest.java
=> GroupDonSimonTutankhamonTest | testDoingSmthDontKnowWhatExactly_Tchernomor()

src/test/java/IrynaKlTest.java
=> add new test

src/test/java/JavanistyTest.java
Add my first test on collaborative project.
=> Class JavanistyTest. Add testAratinveMainMenuTitle

src/test/java/GroupTeamRocketTest.java
Added testSwitchToPageCompareInsuranceQuote_VadimTref in class GroupTeamRocketTes
=> Added testSwitchToPageCompareInsuranceQuote_VadimTref

src/test/java/GroupTeamRocketTest.java
Add testCheckTheMostRelevantBook_AnastasiaKuz
=> Add testCheckTheMostRelevantBook_AnastasiaKuz

src/test/java/GroupTeamRocketTest.java
=> new test added by AnastasiaYakimova

src/test/java/GroupDonSimonTutankhamonTest.java
testFirstNameInputField_SelectorsHubCom, testIfPageSourceContainsHtmlTag_SelectorsHubCom, testSessionId_SelectorsHubCom, testFooter_SelectorsHubCom
=> remove unstable tests, resolve conflict, add new tests

src/test/java/GroupFremenTest.java
Add testMenuComponentsContainsListOfAllTheComponents() and testMainPageContainsListOfAllTheComponents().
=> Added tests: menu and main page contain list of all the components.

src/test/java/GroupFremenTest.java
add two new tests for Web Form from Vera, group Fremen
=> add tests for Web Form

src/test/java/GroupBughuntersTest.java, src/test/java/GroupDonSimonTutankhamonTest.java
Added tests /testСhoosingСlothes, testFillingInContactInformation
=> Nata mona/mats

src/test/java/GroupTeamRocketTest.java
correct testGoToStepTwoForGetQuote_VadimTref and testSwitchToPageCompareInsuranceQuote_VadimTref
=> correct 2 tests

src/test/java/GroupCodeRedTest.java
=> Zinaida test

src/test/java/GroupSqaeTest.java, src/test/java/SpiritMastersTest.java
=> [ADDED] 5 tests and test data

src/test/java/GroupBughuntersTest.java, src/test/java/GroupDonSimonTutankhamonTest.java, src/test/java/GroupFremenTest.java, src/test/java/GroupTeamRocketTest.java
Добавил два новых теста, для сайта https://formy-project.herokuapp.com/  от Dima Zadrutskiy
=> Two test Dima Zadrutski

src/test/java/GroupObukhovTest.java
add testFillFieldsStartPage,
refactoring testCheckHeroButtonColorsAfterNavigateMouse,
add methods getRandomString, getRandomEmail
=> add test and two methods, refactoring code

src/test/java/WondMindsTest.java
=> add test TaniaKuno

src/test/java/GroupTeamRocketTest.java
testBROWSE_LANGUAGES_M_NO added
=> testBROWSE_LANGUAGES_M_NO added

src/test/java/SpiritMastersTest.java
Added test for checkboxes on HerokuApp
=> SpiritMastersGroup | MariaRakhmanava | checkboxes test 

src/test/java/GroupCodeRedTest.java, src/test/java/GroupTeamRocketTest.java, src/test/java/group_a_team/SauceDemoInventoryPageTest.java
check scrolling and auto filling fields , Assert - filling fields
=> Add method - test_scrollPageDownAndFillingFields()

src/test/java/OpenWeatherSearchingCityTest.java
First push in project JenkinsQA_05
=> Timberhut test

src/test/java/GroupTeamRocketTest.java
removed Ignore, xpath corrected, test name changed
=> "test name changed, Xpath corrected"

src/test/java/GroupSpiritMastersTest.java, src/test/java/SpiritMastersTest.java
1. Renamed a group class to GroupSpiritMastersTest
2. Remove an empty string in testTextBoxFields_AFedorova()
=> SpiritMasters| Renamed a group class

src/test/java/GroupWonderingMindsTest.java
=> Happy strawberry/at

src/test/java/GroupSpiritMastersTest.java
=> GroupSpiritMastersTest | Deleted empty string

src/test/java/GroupSpiritMastersTest.java
Refactored test zyzBankRegisterLogin_MW_Test
=> GroupSpiritMastersTest | zyzBankRegisterLogin_MW_Test()

src/test/java/GroupJavanistyTest.java
Refactoring test_IriSamo_Registration
=> Refactoring

src/test/java/GroupBughuntersTest.java, src/test/java/GroupCodeRedTest.java, src/test/java/GroupCubsTest.java, src/test/java/GroupSpiritMastersTest.java, src/test/java/GroupWonderingMindsTest.java
made changes to testBankRegisterLogin_MW
=> GroupSpiritMastersTest | testBankRegisterLogin_MW()

src/test/java/GroupCodeRedTest.java, src/test/java/GroupDreamTeamTest.java
Made a refactoring of all my tests.
=> Refactored tests

src/test/java/GroupCodeRedTest.java, src/test/java/GroupTeamRocketTest.java, src/test/java/NoGroupTest.java
Code refactor for Andrew, Olga, Tina, Michael
=> GroupCodeRed Refactor - group therapy

src/test/java/GroupObukhovTest.java
refactoring code,
create getWait() method,
add testCheckRoundButtonHelpMenuLinkToTelegram and testCheckRoundButtonHelpMenuLinkToLiveChat
=> refactoring code, add tests

src/test/java/GroupSpiritMastersTest.java
Refactored test for checkboxes on HerokuApp
=> SpiritMastersGroup | MariaRakhmanava | Herokuapp checkboxes page test refactoring

src/test/java/GroupJavanistyTest.java
refactoring test_Registration_IriSamo
=> refactoring for GroupJavanistyTest

src/test/java/GroupQAGangTest.java
Created method: testTextTitlePageApi_PaulLiberman , for training git skills.
=> just test of pushing

src/test/java/GroupTeamRocketTest.java
testFindTitleGuide_NataliiaOliver() has been edited, line beakes has been fixed
=> testFindTitleGuide_NataliiaOliver() edited, line beakes fixed

src/test/java/GroupTeamRocketTest.java
Added testCountAndNamesOfRadioButtons_VadimTref and fixed 2 tests
=> Added testCountAndNamesOfRadioButtons_VadimTref and fixed 2 tests

src/test/java/GroupBughuntersTest.java, src/test/java/GroupSpiritMastersTest.java
=> second commit

src/test/java/GroupQAGangTest.java, src/test/java/GroupSqaeTest.java
=> two tests - refactor, 3th test new

src/test/java/MariJernTest.java
added new testH2PopUpText to MariJernTest class
=> added new testH2PopUpText

src/test/java/GroupWonderingMindsTest.java
=> test 99 bottles start menu

src/test/java/GroupSqaeTest.java, src/test/java/GroupWonderingMindsTest.java
testFindSubMenuTeam_TsetskL add, double Ignore delite in /GroupSqaeTest
=> testFindSubMenuTeam_TsetskL add, double Ignore delite in /GroupSqaeTest

src/test/java/GroupFremenTest.java, src/test/java/GroupObukhovTest.java
- added two tests to groupclass
=> added tests to group class

src/test/java/GroupTeamRocketTest.java
The testSignGuestbookTest_NO() has been edited, line breaks have been fixed
=> testSignGuestbookTest_NO() edited, line breaks fixed (GroupTeamRocket)

src/test/java/GroupJavanistyTest.java
Putting testH2TagText_WhenSearchingCityCountry() toIgnore, need more sleepTime
=> testH2TagText_WhenSearchingCityCountry() Ignored

src/test/java/GroupCodeRedTest.java
added new testH2PopUpText_WhenClickingCookiesButton
=> MariJern added new testH2PopUpText to GroupCodeRedTest

src/test/java/GroupCodeRedTest.java
Renamed testHerokuApp to testButtonHerokuApp
Moved testButtonHerokuApp FromMariJernTest to GroupCodeRedTest
=> Moved testButtonHerokuApp to GroupCodeRedTest

src/test/java/GroupCodeRedTest.java, src/test/java/GroupCubsTest.java
Refactoring tests: testKirillShumakov, testPochekirya, testLiza, testAsh.
=> Refactoring tests

src/test/java/GroupCubsTest.java, src/test/java/GroupSpiritMastersTest.java
=> refactoring rp5SearchLocation

src/test/java/GroupDreamTeamTest.java
Hello, I added 2 new test to test class.
=> Add 2 new test

src/test/java/GroupTeamRocketTest.java
Tests testTenLanguageStartNumbers_NO and testBrowseLanguagesAlternativeVersions_NO edited, extra blank lines removed, Asserts separeted by blank lines
=> Tests GroupTeamRocket refactored NataliiaOliver

src/test/java/GroupWonderingMindsTest.java
refactoring testAmazingBouqets
=> refactoring testAmazingBouqets

src/test/java/GroupWonderingMindsTest.java
testFindEnglishLanguageInBrowseLanguages(YuliyaShershen) added
=> testFindEnglishLanguageInBrowseLanguages(YuliyaShershen) added

src/test/java/GroupCodeRedTest.java
Removed Ignore from codeRedGroup class
=> codeRedGroup refactor - removed Ignore

src/test/java/GroupObukhovTest.java
remove Ignore from testRoundButtonHelpMenuLinkToLiveChat(), change locator, add wait
=> remove Ignore from testRoundButtonHelpMenuLinkToLiveChat()

src/test/java/GroupTeamRocketTest.java
add a new test for VIN checker into Team Rocket group class
=> add new test for VIN checker

src/test/java/GroupTeamRocketTest.java
tesFindMercedesVinOnJunkYardAndDecodeIt code refactoring
=> TeamRocket RF code test

src/test/java/GroupTeamRocketTest.java
New test Added testStaticDropDown_VZ
=> testStaticDropDown_VZ added

src/test/java/GroupObukhovTest.java
add testHelpsMenuContentAnotherQuestions()
add method getRandomNumber
=> Ach/test urent/add test

src/test/java/GroupOfTwoTest.java
=> GroupOfTwo checkBoxesTest

src/test/java/GroupBughuntersTest.java, src/test/java/NoGroupTest.java
=> NoGroupTest | testModaldialogs_MariaSh()

src/test/java/GroupDreamTeamTest.java
=> fixed test2

src/test/java/GroupDonSimonTutankhamonTest.java
added test test_CheckItemsPriceSortedFromLowToHigh_Snegafal, deleted ignored test, refactored testEnteringNameInAlertAndConfirmation
=> added test test_CheckItemsPriceSortedFromLowToHigh, refactored previous tests

src/test/java/GroupWonderingMindsTest.java
Added testFindLanguageCobra_HappyStrawberry remove text added empty row
=> Added testFindLanguageCobra_HappyStrawberry remove text added empty row

src/test/java/GroupTeamRocketTest.java
=> testStaticDropDown_VZ refactored

src/test/java/GroupJavanistyTest.java
Refactor test_Aratinve_MainMenuTitle. Add test_Aratinve_MainMenuNavigation.
=> Refactor and Add test_Aratinve

src/test/java/GroupLoxyTest.java
=> YM first test added

src/test/java/GroupLoxyTest.java
=> YM LogoSizeTest

src/test/java/GroupJavanistyTest.java
testPageSearchLanguagesUrlAndTitle() added
=> testPageSearchLanguagesUrlAndTitle() added

src/test/java/GroupDreamTeamTest.java, src/test/java/GroupNikkiTest.java
Added:
- test_invalidBookingDarina
- test_invalidBookingDarina
Refactoring: added class variables
=> GroupDreamTeamTest added test_invalidBookingDarina, test_invalidBookingDarina

src/test/java/GroupBugBustersTest.java
Refactoring class GroupBugBustersTest
=> Refactoring class GroupBugBustersTest

src/test/java/NoGroupTest.java
=> NoGroupTest | testGoFormHerokuApp_VeraFes fist test

src/test/java/GroupDreamTeamTest.java
=> New test and refactoring others

src/test/java/GroupTeamRocketTest.java
ScrollbarsTest added ArtCh GroupTeamRocket
=> ScrollbarsTest added

src/test/java/GroupTeamRocketTest.java
RF testFindTitleGuide_NataliiaOliver(), delite sleeps, added wait
=> RF testFindTitleGuide_NataliiaOliver() GroupRocketTeam

src/test/java/GroupTeamRocketTest.java
Fixed XPath in testCountAndNamesOfRadioButtons_VadimTref
=> Fixed XPath in testCountAndNamesOfRadioButtons_VadimTref

src/test/java/GroupCubsTest.java
Added new test
Import actions deleted (not used)
=> AndrewS test2 added

src/test/java/GroupTeamRocketTest.java
RF testFindTitleGuide_NataliiaOliver(), used methods wait
=> RF testFindTitleGuide_NataliiaOliver(), GroupTeamRocket

src/test/java/GroupFremenTest.java
Spaces added, removed unnecessary sleep.
=> refactor testVera_completeWebForm

src/test/java/EugeneSTest.java, src/test/java/GroupBughuntersTest.java, src/test/java/GroupCubsTest.java, src/test/java/GroupDonSimonTutankhamonTest.java, src/test/java/GroupObukhovTest.java, src/test/java/GroupSpiritMastersTest.java, src/test/java/GroupTeamRocketTest.java
Added testFooterHeadersPropertiesAsh
Removed unused import
=> AndrewS test3 added

src/test/java/FolderTest.java, src/test/java/SimpleTest.java
https://trello.com/c/0B9iw2GF/61-at-0004-new-item-folder-create-folder
=> AT 00.04 | New item > Folder> Create Folder

src/test/java/CreateUserVerifyCreateTest.java
https://trello.com/c/HFC4xCSR/57-tc-070101-people-people-create-user
=> AT 07.01.01 | People > People> Create User

src/test/java/FolderTest.java
https://trello.com/c/28hfWiR7/81-at-0402-folder-configure-folder-display-name
=> AT04.02 | Folder > Configure folder display name

src/test/java/NewItemCreatePipelineTest.java
AT https://trello.com/c/5LR5QHGv
TC https://trello.com/c/Jn2hOYQL
US https://trello.com/c/82dOhJQZ
=> NewItemCreatePipelineTest | testCreatePipelineExistingNameError() aded | gdikhsanov

src/test/java/FolderTest.java
https://trello.com/c/28hfWiR7/81-at-0402-folder-configure-folder-display-name
=> AT04.02 | Folder > Configure folder display name second test

src/test/java/CreateUserVerifyCreateTest.java
https://trello.com/c/Gp0UXXYz/76-at-070301-people-people-delete-user)](https://trello.com/c/Gp0UXXYz/76-at-070301-people-people-delete-user
=> AT 07.03.01 | | People > People > Delete user

src/test/java/FolderTest.java
https://trello.com/c/vSx77Zei/106-at-0404-folder-delete-folder
=> AT 04.04 | Folder > Delete Folder

src/test/java/DeleteFolderTest.java
=> AT 04.04.01 | Folder > Delete Folder

src/test/java/FolderTest.java
https://trello.com/c/Nh5XrBBW/90-at-0403-folder-add-folder-description
=> AT 04.03 | Folder > Add folder description

src/test/java/FolderWithoutConfigTest.java
https://trello.com/c/eLOPui8i/158-at-000401-new-item-create-folder-without-configure
=> AT 00.04.01 Create Folder without configure

src/test/java/NewItemCreatePipelineTest.java
=> AT 00.02.04 | New Item > Create Pipeline | Empty name

src/test/java/HeaderLogoTest.java
[AT] - https://trello.com/c/p6loyJVA/159-at-120201-header-logo-name-icon-see-name-icon
=> AT 12.02.01 | 12.02.01 | Header > Logo > Name icon is displayed | testSeeNameIcon

src/test/java/MulticonfigurationProjectTest.java
testCreateMulticonfigurationProject_HappyPath() added
AT - https://trello.com/c/Q8q5tMf5/144-at-000301-new-item-create-multi-configuration-project
=> AT 00.03.01 | New item > Create Multi-configuration Project with Random Name

src/test/java/MultibranchPipelineTest.java, src/test/java/MulticonfigurationProjectTest.java
"test name changed, delete project added, random name changed to specific name
AT - https://trello.com/c/Q8q5tMf5/144-at-000301-new-item-create-multi-configuration-project-with-valid-name-happy-path
=> AT_00.03.01_New_item_Create_Multiconfiguration_Project_With_Valid_Name

src/test/java/FreestyleProjectTest.java
AT - https://trello.com/c/0ZbYAAeo/196-at-0102001-freestyle-project-view-changesno-builds-sign-appears
=> AT 01.02.001 |Freestyle Project > View Changes>“No builds.” sign appears

src/test/java/MulticonfigurationProjectTest.java
code refactored, locators corrected, final variable added
=> RF | MulticonfigurationProjectTest > testCreateMultiConfigurationProjectWithValidName_HappyPath()

src/test/java/NewItemTest.java
[AT] - https://trello.com/c/Xv7KDC6z/145-at-000701-new-item-new-item-page-contains-items-without-created-project
=> AT 00.07.01 | New Item > New Item Page | Contains Items without created project

src/test/java/NewItemCreatePipelineTest.java
https://trello.com/c/aAy21Ea0/148-at-000205-new-item-create-pipeline-check-created-pipeline-on-breadcrumbs
=> AT 00.02.05 | New Item > Create Pipeline | check created pipeline on Breadcrumbs

src/test/java/MultibranchPipelineTest.java
https://trello.com/c/ht0YNzf9/214-at-05042-multibranch-pipeline-create-multibranch-pipeline-with-invalid-name
=> AT 05.04.2 | Multibranch pipeline > Create Multibranch pipeline with invalid name

src/test/java/NewItemCreatePipelineTest.java
https://trello.com/c/rWMbXced/191-at-000209-new-item-emptyname
=> AT 00.02.09 | New item > EmptyName

src/test/java/MulticonfigurationProjectTest.java
method getFirstMCProject removed, spacec added, click added
=> RF_CodeRefactored_in_MulticonfigurationProjectTest

src/test/java/FreestyleProjectTest.java
Optimization of the following classes:
testDeleteFreestyleProject
testViewChangesNoBuildsSignAppears
testRenameFreestyleProject
[Trello](https://trello.com/c/Ll6n647I/257-rf-freestyleprojecttest-class-refactoring-and-optimization)
=> RF | FreestyleProjectTest > Class refactoring and optimization

src/test/java/FolderTest.java, src/test/java/FreestyleProjectTest.java
https://trello.com/c/DCzGEW0C/100-at-0408001-folder-creat-folder-rename-folder
=> AT 04.08.001 | Folder > Creat Folder > Rename folder

src/test/java/UserProfileTest.java
At 15.01.001 user profile page add description
+ removed empty lines
https://trello.com/c/2HGR4MIy/261-at-tc-1501001-user-profile-page-add-description
=> AT 15.01.001 User Profile Page Add Description

src/test/java/MulticonfigurationProjectTest.java
https://trello.com/c/0jufQC14/180-at-030701-multi-configuration-project-delete-multi-configuration-project
=> AT 03.07.01 | Multi-configuration Project > Delete Multi-configuration Project

src/test/java/AddFolderDescriptionTest.java
[AT 04.03.02 | Folder > Add folder description](https://trello.com/c/YurQBx4Z)
=> AT 04.03.02 | Folder > Add folder description

src/test/java/FolderTest.java, src/test/java/FreestyleProjectTest.java, src/test/java/OrganizationFolderTest.java
https://trello.com/c/PSvqRxck/246-at-040702-folder-move-folder-in-folder
=> AT 04.07.02 | Folder > Move folder in folder

src/test/java/OrganizationFolderTest.java
https://trello.com/c/2tcLVhqP/167-at-000603-new-item-organization-folder-create-organization-folder
=> AT 00.06.03 | New item > Organization folder > Create Organization folder

src/test/java/NewItemTest.java
https://trello.com/c/fjSEmOQg/223-at-000702-new-item-new-item-page-verify-go-to-new-item-page
=> AT 00.07.02 | New Item > New Item Page | Verify go to New Item Page

src/test/java/NewItemCreatePipelineTest.java
US - https://trello.com/c/82dOhJQZ
TC - https://trello.com/c/bmw9Siy4
AT - https://trello.com/c/kE4L8Wa7
=> AT 00.02.02 | Pipeline> Create Pipeline

src/test/java/FolderTest.java
https://trello.com/c/H8oxx5VV/294-rf-foldertest-testcreatefreestyleprojectinfolder
Created method for tests
createProjectFromDashboard()
Refactoring locator name
FREESTYLE_PROJECT
Refactoring test
testCreateFreestyleProjectInFolder()
=> RF | FolderTest > testCreateFreestyleProjectInFolder

src/test/java/MulticonfigurationProjectTest.java
Added test for AT 00.03.02 as CreateMultiConfigurationProjectWithDescription
=> AT 00.03.02 New item > Multi-configuration Project> Create

src/test/java/FreestyleProjectTest.java
Delete ignore from FreeStyleProject
=> Check FreestyleProjectTest on CI

src/test/java/PipelineTest.java
[](https://trello.com/c/QcLwsdFL/312-at-021101-pipeline-enable-disable-project-verify-user-can-click-on-disable-project-button-and-see-the-message)
=> AT 02.11.01 | Pipeline > Enable/Disable project > Verify user can click on Disable project button and see the message

src/test/java/OrganizationFolderTest.java
ERR | 00.06.01 | New item > Organization folder > Create Organization folder
=> ERR | 00.06.01 | New item > Organization folder > Create Organization folder

src/test/java/NewItemCreatePipelineTest.java
https://trello.com/c/y80e2MkM/308-rf-newitemcreatepipelinetest-refactoring-all-class
=> RF | NewItemCreatePipelineTest> refactoring all class

src/test/java/FolderTest.java
https://trello.com/c/yvgOT9Zv/309-at-040902-folder-move-freestyle-project-in-folder
Created test:
testMoveFreestyleProjectInFolderUsingDropDownMenu()
=> AT 04.09.02 | Folder > Move Freestyle project in folder

src/test/java/FolderTest.java
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;tpJzqs5c&#x2F;320-at-040202-folder-configure-folder-display-name">AT 04.02.02 | Folder &gt; Configure folder display name</a></blockquote>
=> AT 04.02.02 | Folder > Configure folder display name

src/test/java/FreestyleProjectTest.java
US- https://trello.com/c/rKJ2Bxb1
TC- https://trello.com/c/iTJwnlIL
AT- https://trello.com/c/H8I7emLv
=> AT 01.07.02 | Freestyle Project> Creating Freestyle Project With a Description

src/test/java/FreestyleProjectTest.java
RF- https://trello.com/c/AMecbRQA
added final String description with text "Some Description Text" in method testCreateFreestyleProjectWithDescription
replace text to final String descriptionin in 110 and 115 line number
=> RF | Freestyle Project> Creating Freestyle Project With a Description

src/test/java/FolderTest.java
https://trello.com/c/4rHz6HRf/188-at-040402-folder-delete-folder-using-drop-down
=> test Delete Folder Using DropDown

src/test/java/OrganizationFolderTest.java
https://trello.com/c/EjG0Uyx0/201-at-000604-new-item-organization-folder-create-organization-folder-with-empty-item-name
=> AT 00.06.04 | New item > Organization folder > Create Organization folder with empty Item Name

src/test/java/CreateFolderThenCreatePipelineInItTest.java
https://trello.com/c/kcciSmQu/276-tc-041002-folder-create-pipeline-in-folder
TC 04.10.02 | Folder > Create Pipeline in folder
AT 04.10.02 | Folder > Create Pipeline in folder
=> TC 04.10.02 | Folder > Create Pipeline in folder

src/test/java/PipelineTest.java
https://trello.com/c/nd3U6X9i/330-at-000210-new-item-create-pipeline-check-created-pipline-on-my-views
=> test Created Pipeline Displayed On My Views

src/test/java/CreatePipelineInFolderTest.java
added a test to verify creating pipeline in folder
=> AT_04.10.01 | New item > Create pipeline in folder

src/test/java/FolderTest.java
=> AT 04.11.01 | Folder > Create Multiconfiguration project in folder | Create Multiconfiguration project in folder

src/test/java/FolderTest.java
https://trello.com/c/toVFDr3p/342-at-040301-folder-add-folder-description-with-add-description-option
=> AT 04.03.01 | Folder > Add folder desc with "Add description" option

src/test/java/PeoplePageTest.java
https://trello.com/c/blu1PklS/293-at-070201-people-people-view-people-page
=> AT07.02.01_People>View People page

src/test/java/OrganizationFolderTest.java
=> RF | New item > Organization folder > Create Organization folder

src/test/java/FreestyleProjectTest.java
https://trello.com/c/GitmsFrN/234-tc-010703-freestyle-project-edit-description-of-a-created-freestyle-project
=> AT 01.07.03 | Freestyle Project> Edit Description of a Created Freestyle Project

src/test/java/OrganizationFolderTest.java
(https://trello.com/c/pqNRfkh8/313-at-060501-organization-folder-move-organization-folder)
=> AT 06.05.01 | Organization folder > Move Organization folder

src/test/java/NewItemTest.java
[AT] - https://trello.com/c/9aSS6fiP/322-at-000404-new-item-folder-create-folder
=> AT 00.04.04 | New item > Folder> Create Folder

src/test/java/FolderTest.java
(by option New Item)
https://trello.com/c/O0GlYCRD/343-at-000000-item-sub-item
Created test:
public void testCreateFreestyleProjectInFolderNewItem()
=> AT 04.09.03 | Folder > Create Freestyle project in folder

src/test/java/FolderTest.java
https://trello.com/c/P8YH3VGT/375-rf-foldertest-testcreatefreestyleprojectinfoldercreatejob
Refactoring test
New name: testCreateFreestyleProjectInFolderCreateJob()
=> RF | FolderTest>testCreateFreestyleProjectInFolderCreateJob

src/test/java/NewItemCreatePipelineTest.java
ERR https://trello.com/c/lQwjuxAk
=> ERR | NewItemCreatePipelineTest > testCreatePipelineExistingNameError Fixed | gdikhsanov

src/test/java/MulticonfigurationProjectTest.java
[Trello](https://trello.com/c/kEdavf5F/211-tc-030604-multiconfiguration-project-configure-enable-project)
=> AT 03.06.04 | Multiconfiguration Project > Configure> Enable Project

src/test/java/FreestyleProjectTest.java
https://trello.com/c/Y7YTIL4E/370-at-010101-freestyle-project-view-project-page-check-freestyle-project-name
=> AT 01.01.01 | Freestyle Project > View Project Page > Check Freestyle Project Name

src/test/java/PipelineTest.java
https://trello.com/c/Q8XrgCNy/334-rf-new-item-organization-folder-create-organization-folder
=> RF | PipelineTest> testDisablePipelineProjectMessage

src/test/java/MyViewsTest.java
https://trello.com/c/rnOi5zd2/273-at-100201-my-views-add-description
=> AT 10.02.01 | My views > Add description

src/test/java/HeaderTest.java
testUserDropdownMenuToOpenPageAdminBuilds added, 
[Trello](https://trello.com/c/pkT0muar/359-at-120502-header-user-dropdown-menu-open-page-builds-by-click-on-item-in-user-dropdown-menu)
testCountAndNamesItemsInUserDropdownMenu refactored, 
method openUserDropdownMenu() added
[Trello](https://trello.com/c/ljhm0gyM/363-rf-headertest-testcountandnamesitemsinuserdropdownmenu)
=> AT 12.05.02 | Header > User dropdown menu > Open Page "Builds" 

src/test/java/PipelineTest.java
https://trello.com/c/i87vXr2W/419-at-021001-pipeline-add-description
=> AT 02.10.01 | Pipeline > Add description

src/test/java/FreestyleProjectTest.java
https://trello.com/c/4BSrLNZq/189-at-000105-new-item-freestyle-project-create-freestyle-project-with-engineer-in-name
=> AT 00.01.05 | New item > Freestyle Project> Create Freestyle Project With Engineer In Name

src/test/java/HeaderTest.java
AT - https://trello.com/c/9KuZvMb8/421-at-120101-header-head-icon-verify-that-the-head-icon-is-displayed
TC - https://trello.com/c/e0xoMcib/384-tc-120101-header-head-icon-verify-that-the-head-icon-is-displayed
US - https://trello.com/c/uMoUsu4V/101-us-1201-header-head-icon
=> AT 12.01.01 | Header > Head icon > Verify that the Head icon is displayed

src/test/java/HeaderTest.java
testUserDropdownMenuToOpenPageAdminConfigure added
[Trello](https://trello.com/c/oCot6MMN/360-at-120503-header-user-dropdown-menu-open-page-configure)
=> AT 12.05.03 | Header > User dropdown menu > Open Page "Configure"

src/test/java/FreestyleProjectTest.java
https://trello.com/c/Pi9fKnz7/410-at-010301-freestyle-project-build-now
Created method for test:
getRandomName
createProjectFromDashboard
Created test:
testCreateBuildNowOnFreestyleProjectPage()
=> AT_01.03.01 | Freestyle_Project > BuildNow

src/test/java/NewItemCreatePipelineTest.java
refactored testDeletePipelineFromDashboard() after fail
[ERR] - https://trello.com/c/1uJHBNDp/430-err-newitemcreatepipelinetest-testdeletepipelinefromdashboard
=> ERR | NewItemCreatePipelineTest > testDeletePipelineFromDashboard

src/test/java/FreestyleProjectTest.java
AT - https://trello.com/c/HqCNIGCm
=> AT 01.01.01 | Freestyle Project > View Project Page > Verify that the freestyle project page is opening from the dashboard list

src/test/java/HeaderTest.java
testUserDropdownMenuToOpenPageAdminMyViews added
[Trello][(url](https://trello.com/c/9fg9CX3U/361-at-120504-header-user-dropdown-menu-open-page-myviews))
=> AT 12.05.04 | Header > User dropdown menu > Open Page "MyViews"

src/test/java/NewItemCreatePipelineTest.java
deleted @Ignore from testDeletePipelineFromDashboard()
[ERR] - https://trello.com/c/1uJHBNDp/430-err-newitemcreatepipelinetest-testdeletepipelinefromdashboard
=> ERR  | NewItemCreatePipelineTest > testDeletePipelineFromDashboard

src/test/java/MulticonfigurationProjectTest.java
add testCreateNewMCProjectAsCopyFromExistingProject()
[AT] - https://trello.com/c/07tNRMn2/441-at-000801-new-item-copy-from-create-a-new-item-from-existing-project-with-the-same-properties
=> AT 00.08.01 New item > Copy from > Create a new item from existing project with the same properties

src/test/java/HeaderTest.java
testUserDropdownMenuToOpenPageAdminCredentials added
[Trello](https://trello.com/c/Z5aGvgek/362-at-120505-header-user-dropdown-menu-open-page-credentials)
=> AT 12.05.05 | Header > User dropdown menu > Open Page "Credentials"

src/test/java/BuildHistoryTest.java
AT - https://trello.com/c/nV3gVXav/453-at-080101-build-history-open-build-history-page
US - https://trello.com/c/k01jM2s8/431-us-0801-build-history-open-build-history-page
=> Create class BuildHistoryTest for group

src/test/java/CreateUserVerifyCreateTest.java
https://trello.com/c/CzlOuiMJ/399-at-070103-people-people-create-user
=> AT 07.01.03 | People > People> Create User

src/test/java/FreestyleProjectSecondTest.java
https://trello.com/c/8lmSK93K/296-at-0001006-new-item-freestyle-project-createfreestyle-project
=> AT 00.01.006| New Item > FreeStyle Project > CreateFreestyle Project

src/test/java/HeaderTest.java
Added test_Manage_Jenkins_Click_name_icon_to_return_to_the_main_page
AT - https://trello.com/c/OcjQgqiD/437-at-120206-header-logo-name-icon-verify-that-user-redirects-from-manage-jenkins-page-to-the-homepage-by-clicking-the-name-icon
TC - https://trello.com/c/iHY43Xe9/315-tc-120206-header-logo-name-icon-verify-that-user-redirects-from-manage-jenkins-page-to-the-homepage-by-clicking-the-name-icon
US - https://trello.com/c/Mvn2nY2Q/102-us-1202-header-logo-name-icon
=> AT 12.02.06| Header > Logo > Name icon > Verify that user redirects from "Manage Jenkins" page to the homepage by clicking the Name icon

src/test/java/OrganizationFolderTest.java
https://trello.com/c/oxTvwu5f/458-rf-organizationfoldertest-class-testmoveorgfoldertofolder
=> RF: OrganizationFolderTest class - testMoveOrgFolderToFolder test

src/test/java/HeaderTest.java
AT - https://trello.com/c/tRIWpz8b/491-at-120103-header-head-icon-verify-returning-from-new-item-page-to-homepage-by-clicking-on-head-icon
TC - https://trello.com/c/Phoz92ZU/451-tc-120103-header-head-icon-verify-returning-from-new-item-page-to-homepage-by-clicking-on-head-icon
US - https://trello.com/c/uMoUsu4V/101-us-1201-header-head-icon
=> AT 12.01.03 | Header > Head icon > Verify returning from New Item page to homepage by clicking on Head icon

src/test/java/FolderTest.java
https://trello.com/c/sS1Op1HH/493-err-foldertest-configurefolderdisplaynamesavefirstname
=> ERR | FolderTest > ConfigureFolderDisplayNameSaveFirstName remove ignore

src/test/java/CreateListViewTest.java, src/test/java/FolderTest.java
New class for US 11.05  New view > Create new view as List View with extra settings
https://trello.com/c/HzKzMwGc
=> CreateListViewTest class created

src/test/java/FreestyleProjectSecondTest.java
https://trello.com/c/GSz3ekhE/303-at-0107004-freestyle-project-add-description-to-freestyle-project
=> AT 01.07.004 | Freestyle Project> Add Description to Freestyle Project

src/test/java/OrganizationFolderTest.java
[ERR | OrganizationFolderTest > testDeleteOrganizationFolder](https://trello.com/c/hIAnaOSa/467-err-organizationfoldertest-testdeleteorganizationfolder)
and 
[ERR|OrganizationFolderTest>testMoveOrgFolderToFolder](https://trello.com/c/byBdt8Te/503-err-organizationfoldertest-testmoveorgfoldertofolder)
=> ERR|OrganizationFolderTest>testDeleteOrganizationFolder and ERR|OrganizationFolderTest>testMoveOrgFolderToFolder

src/test/java/FreestyleProjectSecondTest.java
https://trello.com/c/5G3AiLQJ/508-at-000109-new-item-freestyle-project-create-freestyle-project-using-valid-name
=> AT 00.01.09 | New item > Freestyle Project> Create Freestyle Project Using Valid Name

src/test/java/FreestyleProjectTest.java
https://trello.com/c/x05zYiK7/481-at-000108-new-item-freestyle-project-create-freestyle-project-with-the-duplicate-name
=> AT 00.01.08 | New Item > Freestyle Project > Create Freestyle Project with the duplicate name.

src/test/java/BuildHistoryTest.java
[AT] - https://trello.com/c/WfeJPQ3P/474-at-000000-new-item-sub-item
[TC] - https://trello.com/c/8cKwypDr/270-tc-120205-header-logo-name-icon-verify-that-user-redirect-from-build-history-page-to-the-homepage-by-clicking-the-name-icon
[US] -https://trello.com/c/Mvn2nY2Q/102-us-1202-header-logo-name-icon
test VerifyRedirectToMainPage added
=> AT 12.02.05 | Header > Redirect from the "Build History" page to the homepage

src/test/java/FreestyleProjectTest.java
https://trello.com/c/KWHpT7q9/514-rf-classname-testname
Deleted methods for test:
getRandomName()
createProjectFromDashboard()
Refactoring test:
testCreateBuildNowOnFreestyleProjectPage()
=> RF | Freestyle Project > Build Now

src/test/java/CreateListViewTest.java
AT - https://trello.com/c/j1woQa1Q
=> AT 11.05.01 | New view > Create new view as List View with extra settings > Create new view with existing jobs

src/test/java/NewItemCreatePipelineTest.java, src/test/java/runner/BaseTest.java, src/test/java/runner/ProjectUtils.java, src/test/java/runner/order/OrderForTests.java, src/test/java/runner/order/OrderForTestsTest.java, src/test/java/runner/order/OrderUtils.java
https://trello.com/c/VjAGQMUS/521-f-160101-delete-all-jobs
=> F 16.01.01 | Delete all jobs

src/test/java/FreestyleProjectSecondTest.java
=> AT 01.04.04 | Freestyle project > Configure > Configure Freestyle project Old Builds option with Days to keep Builds

src/test/java/MulticonfigurationProjectTest.java
Added test FindMultiConfigurationProject to the class MulticonfigurationProjectTest
Checked the project search tool
=> AT 00.03.03 | Multi-configuration project > Find created Multi-configuration project Happy Path

src/test/java/CopyItemTest.java, src/test/java/FolderTest.java
[AT 00.08.02 | New item > Copy from > Create a new item from a not existing item name](https://trello.com/c/co0otqaV/438-at-000802-new-item-copy-from-create-a-new-item-from-a-not-existing-item-name) 
and added `@Ignore` in the methode `testConfigureFolderDisplayNameSaveFirstName()`
[ERR | FolderTest > ConfigureFolderDisplayNameSaveFirstName](https://trello.com/c/sS1Op1HH/493-err-foldertest-configurefolderdisplaynamesavefirstname)
=> AT 00.08.02 | New item > Copy from > Create a new item from a not existing item name

src/test/java/FolderTest.java
https://trello.com/c/sS1Op1HH/493-err-foldertest-configurefolderdisplaynamesavefirstname
=> ERR | FolderTest > ConfigureFolderDisplayNameSaveFirstName

src/test/java/HeaderTest.java
[US] - https://trello.com/c/Mvn2nY2Q/102-us-1202-header-logo-name-icon
[TC] - https://trello.com/c/Cp87jthm/225-tc-120203-header-logo-click-on-name-icon-return-to-main-page
[AT] - https://trello.com/c/yIv8F7UU/513-at-1202-header-logo-name-icon-is-displayed
=> AT 12.02.07_Header_Logo_Click on the Icon Name, the user is returned to the main page

src/test/java/MulticonfigurationProjectTest.java
add testCreateMultiConfigurationProjectDisabled
in class MulticonfigurationProjectTest
=> AT 00.03.04 | New item > Multi-configuration Project> Create Disabled Multi-configuration Project

src/test/java/FreestyleProjectTest.java
https://trello.com/c/kFCSEdkW/372-at-010302-freestyle-project-build-now-build-scheduled
=> AT 01.03.02 | Freestyle Project > Build Now> Build scheduled

src/test/java/OrganizationFolderTest.java, src/test/java/runner/BaseTest.java, src/test/java/runner/order/OrderForTestsTest.java, src/test/java/runner/order/OrderUtils.java
https://trello.com/c/jM35BUkr/538-err-160102-delete-all-jobs
=> ERR | 16.01.02 | Delete all jobs

src/test/java/FreestyleProjectTest.java
https://trello.com/c/0xKPKMZ4/554-at-010603-freestyle-project-rename-freestyle-project-to-incorrect
Added testRenameFreestyleProjectWithIncorrectName()
=> AT 01.06.03 | Freestyle Project> Rename Freestyle Project to incorrect

src/test/java/FreestyleProjectTest.java
https://trello.com/c/PDNFt9wf/539-tc-000112-new-item-freestyle-project-create-freestyle-project
=> TC 00.01.12 | New item > Freestyle Project> Create Freestyle Project

src/test/java/FreestyleProjectTest.java
Added testFreestyleProjectSideMenu()
=> AT 01.04.05 | Freestyle project > Configure | SideMenu

src/test/java/FreestyleProjectSecondTest.java
[AT] : https://trello.com/c/9DvERyFh
=> AT 01.04.06 | Freestyle project > Configure > Configure Freestyle Project Old Builds with Max # of builds to keep

src/test/java/NewItemCreatePipelineTest.java
https://trello.com/c/q95jUGZR/511-at-020404-pipeline-configure-pipeline-adding-git-repository
=> AT 02.04.04 | Pipeline > Configure Pipeline > Adding Git-repository

src/test/java/runner/BaseTest.java, src/test/java/runner/JenkinsUtils.java
https://trello.com/c/hqLJGhrj/583-f-160102-delete-all-views
=> F 16.01.02 | Delete all views

src/test/java/FreestyleProjectTest.java
[Trello](https://trello.com/c/9ANJnnCT/553-at-010403-freestyle-project-configure-see-the-sections-in-the-main-panel-on-the-configuration-page)
Add a new testFreestyleProjectConfigureMenu, change testCreateNewFreestyleProjectWithDupicateName dependency due to adding a new test to the chain
=> AT 01.04.03 | Freestyle project > Configure > See the sections in the Main Panel on the Configuration Page

src/test/java/MulticonfigurationProjectTest.java
=> add tesCheckIconDashboardPage

src/test/java/ManageJenkinsTest.java
https://trello.com/c/Yv3dJcIZ/589-at-090202-manage-jenkins-security-manage-users-rename-full-name
Class created for the test:
ManageJenkinsTest
Test created:
testRenameFullUserName()
=> AT 09.02.02 | Manage Jenkins>Security>Manage Users>Rename Full Name

src/test/java/FolderTest.java
added testCreateFreestyleProjectInFolderByNewItemDropDownInCrambMenu().
[AT] https://trello.com/c/Hiy0nabb
=> AT 04.09.04 | Folder > Create Freestyle project in folder(by New Item drop down menu in crambmenu)

src/test/java/FolderTest.java
[RF] https://trello.com/c/oQw1FZtl
=> RF | FolderTest> testCreateMultiConfigurationProjectInFolder

src/test/java/OrganizationFolderTest.java
https://trello.com/c/qxXt1Vk7/549-rf-organizationfoldertest-depends-on-methods
=> RF | OrganizationFolderTest> depends on methods

src/test/java/FolderWithoutConfigTest.java
https://trello.com/c/GibPA5fD/576-040905-folder-create-freestyle-project-in-folderby-option-create-a-job
=> AT 04.09.05 | Folder > Create Freestyle project in folder(by option Create a job)

src/test/java/MulticonfigurationProjectTest.java
add testMultiConfigurationProjectRenameToInvalidNameViaSideMenu
=> TC 03.09.03 | Multi-configuration Project > Rename Project to an invalid name via side menu>

src/test/java/FolderWithoutConfigTest.java
https://trello.com/c/CTMa2N5o/578-at-041401-folder-deleting-freestyle-project-from-a-folder
=> AT 04.14.01 | Folder > Deleting freestyle project from a folder

src/test/java/OrganizationFolderTest.java
https://trello.com/c/KeRWFIDg/585-at-060502-organization-folder-move-organization-folder-to-dashboard
=> AT 06.05.02 | Organization folder > Move Organization folder to dashboard

src/test/java/ManageJenkinsTest.java
<blockquote class="trello-card"><a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;o6qD3klU&#x2F;606-at-090401-manage-jenkins-troubleshooting-manage-old-data-no-data">AT 09.04.01 | Manage Jenkins &gt; Troubleshooting &gt; Manage Old Data (No data)</a></blockquote>
=> AT 09.04.01 | Manage Jenkins > Troubleshooting > Manage Old Data (No data)

src/test/java/FolderTest.java
Added dependencies to testDeleteFolder2
=> RF | FolderTest > testDeleteFolder2 > depends on methods

src/test/java/ManageJenkinsTest.java
AT - https://trello.com/c/U9x0uom9
=> AT 09.02.01 | Manage Jenkins > Security > Manage Users >Rename User's Full Name

src/test/java/PeopleTest.java
https://trello.com/c/mtwjuMtH/572-at-070105-people-people-create-user
=> AT 07.01.05 | People > People> Create User

src/test/java/PipelineTest.java
[ADDED] testRenamePipelineWithValidName
=> AT 02.08.01 | Pipeline > Rename Pipeline > Rename Pipeline with valid name

src/test/java/HeaderTest.java
Added test_Logo_HeadIcon_ReloadMainPage
AT - https://trello.com/c/W6WQDFCQ/644-at-120102-header-head-icon-verify-that-the-page-reload-by-clicking-head-icon
TC - https://trello.com/c/R1uVIi34/385-tc-120102-header-head-icon-verify-that-the-page-reload-by-clicking-head-icon
US - https://trello.com/c/uMoUsu4V/101-us-1201-header-head-icon
=> AT 12.01.02 | Header > Head icon > Verify that the page reload by clicking Head icon

src/test/java/UserProfileTest.java
AT - https://trello.com/c/HehQI2DI/642-at-1501005-user-profile-page-add-description
testUserProfileHidePreviewDescription () added
=> AT_15.01.005_User_profile_page_Add_Description

src/test/java/MulticonfigurationProjectTest.java
AT 03.02.01.02 | Multiconfiguration Project > Disable Project > Check icon Job name page
=> AT 03.02.01.02 | Multiconfiguration Project > Disable Project > Check icon Job name page

src/test/java/NewItemCreatePipelineTest.java
https://trello.com/c/h9VrdThU/667-at-000211-new-item-pipeline-create-new-pipeline-with-description
=> AT 00.02.11 | New item > Pipeline > Create new Pipeline with description.

src/test/java/MultibranchPipelineTest.java
Created AT for AT 05.05.02 | Multibranch pipeline > Rename Multibranch Pipeline From Drop-down
=> AT 05.05.02 | Multibranch pipeline > Rename Multibranch Pipeline From Drop-down

src/test/java/FreestyleProjectTest.java
[Trello](https://trello.com/c/1p6MdY4p/676-rf-classname-testname)
testFreestyleProjectConfigureByDropdown - replace executeScript with a stronger one
=> RF | FreestyleProjectTest> testFreestyleProjectConfigureByDropdown

src/test/java/BuildHistoryTest.java
AT - https://trello.com/c/CQgBo0b3/628-at-080201-build-history-create-new-project
US - https://trello.com/c/4uEw4Swc/544-us-0802-build-history-create-new-project
=> testCheckValidityCreateBuildOnPage and locators

src/test/java/BuildHistoryTest.java
AT https://trello.com/c/UePoJpwt/702-at-080302-build-history-icon-s-m-l
US https://trello.com/c/ccBIuftM/545-us-0803-build-history-icon-s-m-l)
=> AT 08.03.02 | Build history > icon S, M, L

src/test/java/MulticonfigurationProjectTest.java
https://trello.com/c/3FY8lhJC/569-tc-030109-multi-configuration-project-configure-add-description
=> AT 03.01.09 | Multiconfiguration Project > Configure > add description

src/test/java/BuildHistoryTest.java
AT - https://trello.com/c/35Hl2kyt/708-at-080303-build-history-rss-items-exist
US - https://trello.com/c/ccBIuftM/545-us-0803-build-history-icons
=> AT 08.03.03 | Build history > RSS Items Exist

src/test/java/PipelineTest.java
[ADDED] testRenamedPipelineIsDisplayedInMyViews
=> AT 02.08.03 | Pipeline > Rename Pipeline > Renamed pipeline is displayed in "My Views"

src/test/java/MulticonfigurationProjectTest.java
add test EnableDisabledMulticonfigurationProject
with dependsOnMethod
=> AT 03.02.03 | Multiconfiguration Project > Enable Disabled Multiconfiguration Project

src/test/java/BuildHistoryTest.java
AT - https://trello.com/c/7xsqP6Gl/716-at-080304-build-history-check-if-the-icons-icon-legend-exist
US - https://trello.com/c/ccBIuftM/545-us-0803-build-history-icons
=> AT 08.03.04 | Build History > Check if the icons Icon legend exist

src/test/java/NewItemCreatePipelineTest.java
https://trello.com/c/bgwuCYrP/668-at-000206-new-item-create-pipeline-create-from-existing-job-select-existing-name
=> AT 00.02.06 | New Item > Create Pipeline | Create from existing job select existing name

src/test/java/ListViewTest.java
AT - https://trello.com/c/5j3HmnsV
=> AT 11.03.17 | New view > Edit View > Delete description from List View using the button on the dashboard

src/test/java/NewView1Test.java
new class NewView1Test added,
testCreateMyViews added
[Trello AT](https://trello.com/c/hPid3lzF/710-at-110102-new-view-create-new-view-test-that-some-of-views-were-created)
=> AT 11.01.02 | New view > Create new view > Test that some of views were created

src/test/java/EditViewTest.java
AT 11.03.15 | New view > Edit View > Change the Name on the Existing View Using an Illegal Character from the List of Illegal Characters
Pre-conditions:
Login Jenkins, create a view, start from Dashboard Page.
Steps:
Click on My Views
Click on a View
Click Edit View menu option
Change the view name using an illegal character form the predefined list {"#!@$%^&*:;<>?/[]|\"}
Click the OK button
Repeat the steps for each character in the list until teaching the end of the list
**Expected result: **
There is an error page informing that an illegal character is an unsafe character for each of the characters from the list. A new view is not created
=> AT 11.03.15 | New view > Edit View > Change the Name on the Existing View Using an Illegal Character from the List of Illegal Characters

src/test/java/NewItemCreatePipelineTest.java, src/test/java/runner/TestUtils.java
https://trello.com/c/aOAfDDgn/717-rf-testutils-adding-methods-scrollpagedown-scrolltoelement-waitelementstabilization
=> RF | TestUtils> Adding methods scrollToEnd(), scrollToElement(), elementIsNotMoving()

src/test/java/MultibranchPipelineTest.java
added new test:  testRenameMultiBranchPipelineFromLeftSideMenu 
in a class MultibranchPipelineTest
=> AT 05.05.01 | Multibranch pipeline > Rename Multibranch Pipeline From Left Side Panel

src/test/java/UserProfileTest.java
testUserProfilePreviewDescription() added
[AT] https://trello.com/c/sukz1aqq/643-at-1501004-user-profile-page-preview-description
=> AT 15.01.004 | User Profile Page > Preview Description

src/test/java/NewView1Test.java
testDeleteMyView in class NewView1Test added
[Trello AT](https://trello.com/c/08N2lMcB/712-at-110202-new-view-delete-view-test-that-one-view-was-deleted)
=> AT 11.02.02 | New view > Delete view > Test that one view was deleted

src/test/java/PipelineTest.java
[ADDED] testRenamePipelineWithoutChangingName
=> AT 02.08.04 | Pipeline > Rename Pipeline > Rename pipeline without changing name

src/test/java/NewView1Test.java
testDeleteAllMyViews in class NewView1Test added
[Trello AT](https://trello.com/c/MZgjlRY8/713-at-110203-new-view-delete-view-test-that-all-views-were-deleted)
=> AT 11.02.03 | New view > Delete view > Test that all views were deleted

src/test/java/FreestyleProjectTest.java
Added:  testAccessProjectConfigurationFromTheProjectPage; dependsOnMethod "testFreestyleProjectConfigureMenu"; alertAccept method; deleteFreestyleProject method.
=> AT 01.04.01 | Freestyle project > Configure > Access project configuration from the Project page

src/test/java/UserProfileTest.java
testUserProfileEditDescription added
[AT] https://trello.com/c/kmGETedw/275-at-tc-1501002-user-profile-page-edit-description
=> AT TC 15.01.002 | User profile page > Edit Description

src/test/java/ListViewTest.java
AT - https://trello.com/c/3ebUNYOo
=> AT 11.02.04 | New view > Delete view > Verify that the chosen List View was deleted

src/test/java/FreestyleProjectSecondTest.java
[RF] : https://trello.com/c/WBsb4bpf
correct random value for variables,
add "final" to variables,
add closing DropDown
=> RF | FreestyleProjectSecondTest

src/test/java/BuildHistoryTest.java
added methods and 1 test : testNumberOfColumns_ProjectStatusTable()
AT - https://trello.com/c/2aJ7orwX/690-at-080204-build-history-build-history-page-check-number-of-columns-in-projectstatus-table
US - https://trello.com/c/k01jM2s8/431-us-0801-build-history-open-build-history-page
=> AT 08.02.04 |Build History > Build History Page >check number of columns in Project_Status table

src/test/java/PipelineTest.java
[ADDED] testRenamePipelineUsingSpecialCharacter
=> AT 02.08.02 | Pipeline > Rename Pipeline > Rename pipeline using special character

src/test/java/MultiConfigurationProjectsTest.java
https://trello.com/c/k14U6NPk/659-at-030301-multiconfiguration-project-disable
=> AT03.03.01 Disable Multiconfiguration Project

src/test/java/MulticonfigurationProjectTest.java
add testEnableMultiConfigurationProjectCheckIconDashboardPage
https://trello.com/c/g29rdct5
=> AT 03.02.02.02 | Multiconfiguration Project > Enable Project > Check icon Dashboard page

src/test/java/FreestyleProjectTest.java
testFreestyleProjectConfigureMenu - Test optimization: add Lists, make Assert more informative
=> RF | 01.04.03 | Freestyle project > Configure > See the sections in the Main Panel on the Configuration Page

src/test/java/NewItemCreatePipelineTest.java
Delete dublicates final String with Random name
Edit line breaks
=> RF | NewItemCreatePipelineTest

src/test/java/PipelineTest.java
add testPipelinePreviewDescription
https://trello.com/c/PZCcUngW/497-at-021003-pipeline-add-description-preview-description
=> AT 02.10.03 | Pipeline > Add description > Preview description

src/test/java/NewView1Test.java
testViewHasSelectedTypeGlobalView in class NewView1Test added
[Trello](https://trello.com/c/BOXmyfov/760-at-110103-new-view-create-new-view-verify-that-global-view-was-created-with-selected-type)
=> AT 11.01.03 | New view > Create new view > Verify that Global View was created with selected type

src/test/java/NewView1Test.java
testViewHasSelectedTypeListView in class NewView1Test added
[Trello](https://trello.com/c/8QNMoxkZ/761-at-110104-new-view-create-new-view-verify-that-list-view-was-created-with-selected-type)
=> AT 11.01.04 | New view > Create new view > Verify that List View was created with selected type

src/test/java/FolderTest.java
test createFolderWithDescriptionAndJobPipeline added
=> AT 04.10.03 | Folder > Create Pipeline in folder with description

src/test/java/CreateMultibranchPipelineInFolderTest.java
Create Multibranch pipeline in folder
=> AT 04.12.02 | Folder > Create Multibranch pipeline in folder

src/test/java/PipelineTest.java
add testPipelineHidePreviewDescription
https://trello.com/c/fZ7DS7hA/770-at-021004-pipeline-add-description-hide-preview-description
=> AT 02.10.04 | Pipeline > Add description > Hide preview description

src/test/java/NewItemCreatePipelineTest.java
refactored testDeletePipelineFromDashboard()
=> RF | NewItemCreatePipelineTest > testDeletePipelineFromDashboard

src/test/java/NewViewTest.java
https://trello.com/c/SVwVzMB0/754-at-110502-new-view-create-new-view-as-list-view-with-extra-settings
Created locators for test:
LIST_VIEW_NAME
PROJECT_NAME
RADIO_BUTTON_LIST_VIEW
MULTI_CONFIGURATION_PROJECT
Changed locators for test:
BUTTON_SAVE
NEW_VIEW_TAB
RADIO_BUTTON_MY_VIEW
Created methods for test:
createProjectFromDashboard()
createViewFromDashboard()
Deleted methods for test:
generateRandomName()
createPipelineProject()
Used new universal methods without changing the logical structure of the testCreateNewView()
Created test:
testCreateListViewWithExtraSettings()
=> AT 11.05.02 | New view > Create new view as List View with extra settings

src/test/java/FreestyleProjectTest.java
https://trello.com/c/NEIjrUzH/
=> AT 01.07.005  Freestyle Project> Add Description to Freestyle Project

src/test/java/FreestyleProjectTest.java
Fixed variable value for Name of FS Project in testAccessProjectConfigurationFromTheProjectPage
=> RF_FreestyleProjectTest_testAccessProjectConfigurationFromTheProjectPage

src/test/java/NewItemCreatePipelineTest.java
https://trello.com/c/moTVdizH/512-at-020405-pipeline-configure-pipeline-build-parametrized-project
=> AT 02.04.05 | Pipeline > Configure Pipeline > Build parametrized Project

src/test/java/NewFullNameTest.java
Vorsoba…TC 09.02.01.1 - TC 09.02.01.2
=> AT 09.02.01.1 - TC 09.02.01.2 Manage Jenkins > Security > Manage Users > NewFullNameTest 

src/test/java/NewView1Test.java
[Trello](https://trello.com/c/OXIEIYg8/769-at-100401-my-views-rename-view)
Add testRenameMyView, change dependency of testDeleteMyView
=> AT 10.04.01 | My views > Rename view

src/test/java/BuildHistoryTest.java
Added new method to create job project without description
Added new test to check the presence of a new created job on the Build History timeline
AT: https://trello.com/c/7xsqP6Gl/716-at-080304-build-history-check-if-the-icons-icon-legend-exist
US: https://trello.com/c/ccBIuftM/545-us-0803-build-history-icons
=> AT 08.03.04 | Build history > Job Item Exists on Timeline

src/test/java/ManageJenkinsTest.java
https://trello.com/c/OBTD3zYZ/689-err-managejenkinstest-testrenamefullusername
Removed ignore: ManageJenkinsTest>testRenameFullUserName()
Changed locators in testRenameFullUserName
=> ERR | ManageJenkinsTest >testRenameFullUserName

src/test/java/EditViewTest.java
- renamed finals
- removed "crutches" for stability
- updated utility methods for uniformity and clarity
- slightly redesigned random string usage in naming
- added utility methods that allowed to combine some old ones
- after optimizing removed unused finals
- updated a couple of locators to remove linkage to the text
- visual optimization of long lines
- redesigned scroll and wait functionality
- generally increased test run speed
=> RF | 11.03.02 New view > Edit View

src/test/java/PipelineTest.java
add testPipelineAEditDescription
https://trello.com/c/STsFVsxz/366-tc-021002-pipeline-add-description-edit-the-description
=> AT 02.10.02 | Pipeline > Add description > Edit the description

src/test/java/FreestyleProjectTest.java
AT 00.01.10 | New item > Freestyle Project> Create Freestyle Project using a long name (greater than 255 characters)
=> AT 00.01.10 | New item > Freestyle Project> Create Freestyle Project using a long name (greater than 255 characters)

src/test/java/CopyItemTest.java
AT 00.08.03 | New item > Copy from > Don't display the field 'Copy from' if don't have any items
=> AT 00.08.03 | New item > Copy from > Don't display the field 'Copy from' if don't have any items

src/test/java/NewView1Test.java
testViewHasSelectedTypeMyView, methods getListJobs and goToEditView are added in class NewView1Test
[Trello AT](https://trello.com/c/BldrH4or/762-at-110105-new-view-create-new-view-verify-that-my-view-was-created-with-selected-type)
=> AT 11.01.05 | New view > Create new view > Verify that My View was created with selected type

src/test/java/ProjectsInFolderTest.java
[Trello](https://trello.com/c/W5sZAK1D/790-at-000405-new-item-folder-create-folder)
=> AT 00.04.05 | New item > Folder> Create Folder

src/test/java/FreestyleProjectTest.java
https://trello.com/c/NuiZmfr8/782-rf-classname-testname
new steps and locators in testCreateBuildNowOnFreestyleProjectPage()
=> RF | Freestyle Project > Build NowAdded

src/test/java/OrganizationFolderTest.java
=> RF 06.02.01 | Organization Folder > Configure organization folder

src/test/java/BuildHistoryTest.java
AT - https://trello.com/c/SmLXApoJ/795-at-080205-build-history-create-new-build
US - https://trello.com/c/4uEw4Swc/544-us-0802-build-history-create-new-project
=> AT 08.02.05 | Build History > create new build

src/test/java/ProjectsInFolderTest.java
[Trello](https://trello.com/c/xgrl1T8d/791-at-041301-folder-create-organization-folder-in-folder)
=> AT 04.13.01 | Folder > Create Organization folder in folder

src/test/java/FolderOneTest.java
AT 04.01.03 | Folder > Create Folder with Display Name in folder with Display Name
=> AT 04.01.03 | Folder > Create Folder with Display Name in folder with Display Name

src/test/java/FooterTest.java
AT https://trello.com/c/tjU8RVFC/789-at-130204-footer-manage-jenkins-jenkins-23614-verify-link-is-visible
=> AT 13.02.04 | Footer > Manage Jenkins > Jenkins 2.361.4 > Verify link is Visible

src/test/java/BuildHistoryTest.java, src/test/java/HeaderTest.java, src/test/java/NewItemCreatePipelineTest.java, src/test/java/PipelineTest.java, src/test/java/SimpleTest.java, src/test/java/runner/ProjectUtils.java
https://trello.com/c/lmSZh2zC/773-rf-classname-testname
ignored tests:
testRenamePipelineUsingSpecialCharacter(PipelineTest)
https://trello.com/c/eemLe2r4/793-err-classname-testname
testBuildParametrizedProject(NewItemCreatePipelineTest)
https://trello.com/c/HcTK10Wl/794-err-classname-testname
ignored tests:
testSimple(SimpleTest)
https://trello.com/c/0r0b9xmm/799-err-simpletest-testsimple
testVerifyRedirectToMainPage(BuildHistoryTest)
https://trello.com/c/ZlyaKo9l/798-err-classname-testname
ignored test:
testCheckTheAppropriateSearchResult(HeaderTest)
https://trello.com/c/b0RHWOTz/800-err-classname-testname
=> RF | ProjectUtils > Adding methods createNewItemFromDashboard(), createNewViewFromDashboard()

src/test/java/PeopleTest.java
https://trello.com/c/wjt2fkm3/774-at-070202-people-people-view-people-page
=> AT 07.02.02 | People > People > View People page

src/test/java/PeoplePageTest.java
add testFindUserInThePeopleSection
=> AT 07.01.05 | People > People> Find User in the People Section

src/test/java/MultibranchPipelineTest.java
testDeleteMultibranchPipelineFromFolder added
https://trello.com/c/cm9kBveS/792-at-050301-multibranch-pipeline-delete-multibranch-pipeline
=> AT 05.03.01 | Multibranch pipeline > Delete Multibranch Pipeline

src/test/java/BuildHistoryTest.java
[TC]-https://trello.com/c/iQCpWgLo/802-tc-080204-build-history-delete-build
[AT]-https://trello.com/c/rAPlVw8i/803-at-080204-build-history-delete-build
=> AT08.02.04 | Build history > Delete Build

src/test/java/OrganizationFolderTest.java
https://trello.com/c/erAs1YlD/687-rf-organizationfoldertest-add-waits
=> RF | OrganizationFolderTest > add waits

src/test/java/MultibranchPipelineTest.java
Added "test" in the beginning of the test name
=> RF 05.05.02 | Multibranch pipeline > Rename Multibranch Pipeline From Drop-down

src/test/java/PeoplePageTest.java
=> AT 07.03.02 | People > People > Delete user

src/test/java/FolderOneTest.java
=> RF 04. | Folder > Refactor code

src/test/java/FolderTest.java, src/test/java/model/FolderConfigPage.java, src/test/java/model/HomePage.java
https://trello.com/c/LUoWf4Y4/835-rf-foldertest-testdeletefolderusingdropdown
=> RF | FolderTest > testDeleteFolderUsingDropDown

src/test/java/FreestyleProjectSecondTest.java
waits added
[ERR] - https://trello.com/c/kMRs74px
=> ERR | FreestyleProjectSecondTest

src/test/java/CreateUserVerifyCreateTest.java, src/test/java/MulticonfigurationProjectTest.java, src/test/java/OrganizationFolderTest.java, src/test/java/model/NewItemPage.java, src/test/java/model/OrgFolderConfigPage.java, src/test/java/model/OrgFolderStatusPage.java
https://trello.com/c/Hs4g5cRo/816-rf-organizationfoldertest-testcreateorgfolderwithpom
=> RF | OrganizationFolderTest > testCreateOrgFolderWithPOM

src/test/java/FreestyleProjectTest.java, src/test/java/model/FreestyleConfigSideMenuPage.java, src/test/java/model/FreestyleProjectPage.java, src/test/java/model/HomePage.java
Created:
-FreestyleProjectPage;
-FreestyleConfigSideMenuPage;
Added:
-clickFreestyleName(String name) to HomePage;
Refactored to POM:
-FreestyleProjectTest class | testFreestyleConfigSideMenu()
=> RF | FreestyleProjectTest > testFreestyleConfigSideMenu()

src/test/java/model/StatusPage.java
[Trello](https://trello.com/c/DY3Ac6K4/839-rf-new-class-statuspage)
Add new Class StatusPage according to POM
=> RF | new Class > StatusPage

src/test/java/model/MovePage.java
[Trello](https://trello.com/c/Hpv9Vcoi/840-rf-new-class-movepage)
Add new Class MovePage according to POM
=> RF | new Class > MovePage

src/test/java/PeopleTest.java
https://trello.com/c/irEVvArB/836-rf-peopletest-createusertest
Workaround scroll JS and click JS
=> RF | PeopleTest > createUserTest

src/test/java/NewItemCreatePipelineTest.java, src/test/java/model/HomePage.java, src/test/java/model/NewItemPage.java, src/test/java/model/PipelineConfigPage.java
https://trello.com/c/9iEehDN0/842-rf-newitemcreatepipelinetest-testaddinggitrepository
=> RF | NewItemCreatePipelineTest > testAddingGitRepository()

src/test/java/OrganizationFolderTest.java, src/test/java/model/MultiConfigurationProjectStatusPage.java, src/test/java/model/MulticonfigurationProjectConfigPage.java
add MulticonfigurationProjectConfigPage to POM
add MultiConfigurationProjectStatusPage to POM
[RF] - https://trello.com/c/YpPa06xp/843-rf-multiconfigurationprojectconfigpage
=> RF | MulticonfigurationProject

src/test/java/model/DropdownMenu.java
[Trello](https://trello.com/c/1jJUWL2U/838-rf-new-class-dropdownmenu)
Add new Class DropdownMenu according to POM
=> RF | new Class > DropdownMenu

src/test/java/PeoplePageTest.java
=> ERR | PeoplePageTest

src/test/java/FolderMoveTest.java, src/test/java/model/HomePage.java, src/test/java/model/MovePage.java
[Trello](https://trello.com/c/LCKFUFyy/848-rf-homepage-add-new-methods)
Rf/add new methods home page
=> RF | Folder > Create two new folders and move one folder to other folder with option "Move" in the dropdown

src/test/java/FreestyleProjectSecondTest.java
Ignore removed
[RF] - https://trello.com/c/q0OcDdZF
=> RF | FreestyleProjectSecondTest > Remove Ignore annotation from tests

src/test/java/FreestyleProjectSecondTest.java
[AT] - https://trello.com/c/7yYIQ7Nc
=> AT 01.04.11 | Freestyle project > Configure > Validate that selected "Build periodically" checkbox is selected

src/test/java/NewItemTest.java, src/test/java/model/CreateItemErrorPage.java, src/test/java/model/NewItemPage.java
**Created**
CreateItemErrorPage
**Added to POM**
getErrorMessage() to CreateItemErrorPage
setItemAndClickOk() to NewItemPage
rootMenuDashboardLinkClick() to NewItemPage
getItemsListSize() to NewItemPage
**Added to Tests**
NewItemTest > testCreateAnyItemWithSpacesOnlyNameError()
‌
=> AT | NewItemTest > testCreateAnyItemWithSpacesOnlyNameError Added | gdikhsanov #953

src/test/java/FreestyleProjectTest.java, src/test/java/MyViewsTest.java, src/test/java/model/FreestyleProjectConfigPage.java, src/test/java/model/FreestyleProjectPage.java, src/test/java/model/HomePage.java, src/test/java/model/NewItemPage.java
https://trello.com/c/OAsF1uEt/845-rf-freestyleprojecttest-testcreatenewfreestyleproject
=> RF | FreestyleProjectTest> testCreateNewFreestyleProject

src/test/java/NewView1Test.java
Remove Ignore from testDeleteAllViews;
Remove method getListButtonsForJobsDropdownMenu(); 
Remove method deleteAllJobsByDropdownMenus() and it's calling from testDeleteAllViews()
[ERR Trello](https://trello.com/c/h1wsF0AD/822-err-newview1test)
=> ERR | NewView1Test

src/test/java/MultibranchPipelineTest.java
RF 05.05.02 | Multibranch pipeline > Rename Multibranch Pipeline From Drop-down - v2
=> RF 05.05.02 | Multibranch pipeline > Rename Multibranch Pipeline From Drop-down - v2

src/test/java/NewView1Test.java
[Trello](https://trello.com/c/OaKzpU3A/869-rf-my-views-rename-view)
Change xpath
=> RF | My views > Rename view

src/test/java/FreestyleProjectTest.java
Fixed getWait() method in:
testAccessProjectConfigurationFromTheProjectPage; 
deleteFreestyleProject().
=> ERR_FreestyleProjectTest_testAccessProjectConfigurationFromTheProjectPage

src/test/java/NewViewTest.java
https://trello.com/c/OBTD3zYZ/689-err-managejenkinstest-testrenamefullusername
https://trello.com/c/WdjDgoCv/862-rf-classname-testname
Removed ignore:
testCreateListViewWithExtraSettings()
Used getWait() from TestUtils:
testCreateListViewWithExtraSettings()
Used createNewItemFromDashboard() from ProjectUtils:
testCreateNewView()
testCreateListViewWithExtraSettings()
Used createNewViewFromDashboard() from ProjectUtils:
testCreateNewView()
testCreateListViewWithExtraSettings()
=> ERR | NewViewTest > testCreateListViewWithExtraSettings()

src/test/java/FolderTest.java
https://trello.com/c/diaRpd1e/828-err-foldertest
https://trello.com/c/Mt003H9Z/860-rf-foldertest
https://trello.com/c/gDDvfnXd/861-rf-foldertest-testmovefreestyleprojectinfolderusingdropdownmenu
Removed ignore and added getWait() on the testMoveFreestyleProjectInFolderUsingDropDownMenu() and changed Actions to just click.
Deleted methods:
getRandomName()
createProjectFromDashboard()
Changed tests wich using those methods:
testCreateFreestyleProjectInFolderCreateJob()
testCreateMultiConfigurationProjectInFolder()
testCreateFolderInFolder()
testMoveFreestyleProjectInFolderUsingDropDownMenu() testConfigureFolderDisplayNameWithDropdownMenu()
testAddFolderDescription()
testCreateFreestyleProjectInFolderNewItem()
testCreateFreestyleProjectInFolderByNewItemDropDownInCrambMenu()
=> ERR | FolderTest

src/test/java/FreestyleProjectSecondTest.java
add getWait() into testVerifyOptionsInBuildStepsSection
https://trello.com/c/FLg0YDLo
=> ERR | FreestyleProjectSecondTest > testVerifyOptionsInBuildStepsSection

src/test/java/HeaderTest.java
=> Add getWait() and ExpectedConditions.elementToBeClickable into method createOrganizationFolder

src/test/java/ManageJenkinsTest.java
=> ERR | ManageJenkinsTest > testRenameUsersFullName

src/test/java/BuildHistoryTest.java, src/test/java/FolderMoveTest.java, src/test/java/FreestyleProjectTest.java, src/test/java/MultiConfigurationProjectsTest.java, src/test/java/MultibranchPipelineTest.java, src/test/java/NewView1Test.java, src/test/java/model/NewItemPage.java
I first had to return this test (merged in #534 ) as it was deleted by @Reinar47 in #651 PR (evidently by mistake) + refactored according to POM model
=> RF | MultibranchPipelineTest > testCreateMbPipelineEmptyName

src/test/java/model/DropdownMenu.java
[Trello](https://trello.com/c/ZFoKJlUn/875-rf-dropdownpage-add-getwait)
Add getWait method
=> RF | DropdownPage > add getWait

src/test/java/FolderMoveTest.java, src/test/java/FreestyleProjectSecondTest.java, src/test/java/runner/TestUtils.java
https://trello.com/c/kpkvB9yI/881-rf-testutils-overloading-elementisnotmovingfinal-webelement-webelement
=> RF | TestUtils> overloading elementIsNotMoving(final WebElement webElement)

src/test/java/OrganizationFolderTest.java
Add getWait(5) ExpectedConditions.elementToBeClickable
https://trello.com/c/Bo1XnZYY
=> ERR | OrganizationFolderTest > testCreateOrganizationFolderWithCheckOnDashbord

src/test/java/FolderMoveTest.java, src/test/java/model/FolderStatusPage.java, src/test/java/model/HomePage.java, src/test/java/model/MovePage.java
[Trello](https://trello.com/c/AEpvnPz8/874-rf-statuspage-rename)
Rename StatusPage Class to FolderStatusPage
=> RF | StatusPage> Rename

src/test/java/FolderMoveTest.java
[Trello](https://trello.com/c/l6WDa2Uq/891-rf-foldermovetest-testmovefoldertofolder)
Delete Ignore from testMoveFolderToFolder
Added getWait method to solve this problem in pull request #966
=> RF | FolderMoveTest > testMoveFolderToFolder

src/test/java/EditViewTest.java, src/test/java/FreestyleProjectSecondTest.java, src/test/java/ManageJenkinsTest.java, src/test/java/model/ConfigureUserPage.java, src/test/java/model/HomePage.java, src/test/java/model/ManageJenkinsPage.java, src/test/java/model/ManageUsersPage.java, src/test/java/model/StatusUserPage.java
https://trello.com/c/Y4PnmEgE/886-rf-classname-testname
RF test in POM and added another assert with H1 text.
Classes created for the test in POM:
ConfigureUserPage
ManageJenkinsPage
ManageUsersPage
StatusUserPage
=> RF | ManageJenkinsTest > testRenameFullUserName() POM

src/test/java/FreestyleProjectSecondTest.java
getWait() added into testVerifyOptionsInBuildStepsSection()
[RF] - https://trello.com/c/j4bA5he1
=> RF | FreestyleProjectSecondTest > testVerifyOptionsInBuildStepsSection()

src/test/java/FreestyleProjectTest.java, src/test/java/NewItemCreatePipelineTest.java, src/test/java/model/HomePage.java, src/test/java/model/PipelineProjectPage.java
rename clickFreestyleProjectName()
created:
- PipelineProjectPage
- clickPipelineProjectName()
- editDescription(String text)
- clickSaveButton()
- getDescription(String name)
- testEditPipelineDescription()
added locators to PipelineProjectPage:
- editDescriptionButton
- descriptionArea
- saveButton
- description
=> AT 02.10.05 | Pipeline > Add description > Edit the description

src/test/java/MulticonfigurationProjectTest.java
Fixed:  getWait() method in testCreateMultiConfigurationProjectWithDescription; 
bad locator; 
name of the test
=> ERR_MulticonfigurationProjectTest_CreateMultiConfigurationProjectWithDescription

src/test/java/NewItemCreatePipelineTest.java, src/test/java/OrganizationFolderTest.java, src/test/java/model/FolderConfigPage.java
https://trello.com/c/8RAY0vji/901-rf-organizationfoldertest-testcreatefolderwithpom
=> RF | OrganizationFolderTest> testCreateFolderWithPOM

src/test/java/HeaderTest.java
Remove Ignore from 5 tests;
Change locator in method openUserDropdownMenu() 
Add waiters and change locators in 5 tests:
testCountAndNamesItemsInUserDropdownMenu, testUserDropdownMenuToOpenPageAdminBuilds, testUserDropdownMenuToOpenPageAdminConfigure, testUserDropdownMenuToOpenPageAdminMyViews, testUserDropdownMenuToOpenPageAdminCredentials;
=> ERR | HeaderTest

src/test/java/OrganizationFolderTest.java
=> RF Create OrganizFolder POM

src/test/java/NewView1Test.java
Correct lines 110, 118 in testCreateMyViews;
[RF Trello](https://trello.com/c/k1IH0KRj/909-rf-newview1test-testcreatemyviews)
=> RF | NewView1Test > testCreateMyViews

src/test/java/EditViewTest.java, src/test/java/model/EditViewPage.java, src/test/java/model/FolderConfigPage.java, src/test/java/model/HomePage.java, src/test/java/model/MyViewsPage.java, src/test/java/model/NewItemPage.java, src/test/java/model/NewViewPage.java
RF|EditViewTest
Refactored test testGlobalViewAddFilterBuildQueue in EditViewTest class to POM
Made necessary changes in the related Pages: MyViewsPage, FolderConfigPage, NewViewPage, HomePage, EditViewPage, NewItemPage
Made minor refactoring changes in testGlobalViewAddFilterBuildQueue
=>  RF|EditViewTest 

src/test/java/EditViewTest.java, src/test/java/runner/BaseTest.java
Swapped 2 lines ##58 and 59 because the previous order did not allow for deleting views. Have verbal confirmation from SergeyD to initiate the change. Only SergeyD can approve, please refrain from approving this commit unless you are authorized by SergeyD
=> RF|BaseTest->clearData

src/test/java/MultibranchPipelineTest.java, src/test/java/model/DeleteMultibranchPipelinePage.java, src/test/java/model/FolderStatusPage.java, src/test/java/model/MultibranchPipelineConfigPage.java, src/test/java/model/MultibranchPipelineStatusPage.java, src/test/java/model/NewItemPage.java
Changed testDeleteMultibranchPipelineFromFolder into POM;
DeleteMultibranchPipelinePage class created;
MultibranchPipelineStatusPage class created;
created MultibranchPipelineConfigPage class created;
clickCreateJob, clickMultibranchPipeline, getEmptyStateBlock methods added into FolderStatusPage class added;
https://trello.com/c/CdiSgUsx/905-rf-multibranch-pipeline-delete-multibranch-pipeline
=> RF | Multibranch pipeline > Delete Multibranch Pipeline

src/test/java/NewItemCreatePipelineTest.java, src/test/java/model/NewItemPage.java
https://trello.com/c/vGXtowW9/898-rf-newitemcreatepipelinetest-testcreatenewitemwithunsafecharactersname
=> RF | NewItemCreatePipelineTest > testCreateNewItemWithUnsafeCharacterName

src/test/java/MulticonfigurationProjectTest.java, src/test/java/model/HomePage.java, src/test/java/model/MultiConfigurationProjectStatusPage.java
[Trello](https://trello.com/c/xGvMHo9X/917-rf-multiconfigurationprojecttest-testmulticonfigurationprojectadddescription)
=> RF | MulticonfigurationProjectTest > testMulticonfigurationProjectAddDescription

src/test/java/NewItemCreatePipelineTest.java, src/test/java/model/NewItemPage.java
NewItemCreatePipelineTest
- testCreatePipelineExistingNameError() refactored to Pom 
NewItemPage
- getNameErrorMessageText() renamed
- nameErrorMessage renamed
=> RF_NewItemCreatePipelineTest_testCretePipelineExistingNameError_gdikhsanov

src/test/java/FreestyleProjectSecondTest.java
refactoring checking checkbox in testSelectBuildPeriodicallyCheckbox()
refactoring selecting DropDown in testVerifyOptionsInBuildStepsSection()
[RF] - https://trello.com/c/IZRsMXfz
=> RF | FreestyleProjectSecondTest> testSelectBuildPeriodicallyCheckbox, testVerifyOptionsInBuildStepsSection

src/test/java/NewView1Test.java, src/test/java/model/EditViewPage.java, src/test/java/model/MyViewsPage.java, src/test/java/model/ViewPage.java
[Trello](https://trello.com/c/s35fEp7p/920-rf-newview1test-testrenamemyview)
Refactor testRenameMyView (NewView1Test) to POM, add new Class ViewPage
=> RF | NewView1Test > testRenameMyView

src/test/java/FreestyleProjectTest.java, src/test/java/model/FreestyleProjectPage.java
https://trello.com/c/YJpoupCA/924-rf-freestyleprojecttest-testdeletefreestyleproject-pom
REF testDeleteFreestyleProject to POM
remove testRenameFreestyleProject to dependency chain
create clickButtonDeleteProject and confirmAlertAndDeleteProject methods on FreestyleProjectPage
=> REF testDeleteFreestyleProject to POM

src/test/java/FolderTest.java, src/test/java/model/FolderStatusPage.java, src/test/java/model/FreestyleProjectPage.java
[RF] - https://trello.com/c/I0egG59X
=> RF testCreateFreestyleProjectInFolderByNewItemDropDownInCrambMenu to POM

src/test/java/NewView1Test.java
correct CONST's names;
add CONST BY_LIST_VIEWS;
delete method getListViews();
fix code in testDeleteAllViews();
[RF Trello](https://trello.com/c/XmNdouSy/934-rf-newview1test-testdeleteallviews)
=> RF | NewView1Test > testDeleteAllViews

src/test/java/FreestyleProjectSecondTest.java, src/test/java/model/FreestyleProjectConfigPage.java
Refactored to POM: testConfigurationProvideKeepMaxNumberOfOldBuilds()
[RF] - https://trello.com/c/phETYU8K
=> RF | FreestyleProjectSecondTest > refactoring testConfigurationProvideKeepMaxNumberOfOldBuilds to POM

src/test/java/MulticonfigurationProjectTest.java, src/test/java/model/FolderConfigPage.java, src/test/java/model/MultiConfigurationProjectStatusPage.java, src/test/java/model/MulticonfigurationProjectConfigPage.java
RF to POM: testCreateMultiConfigurationProjectWithDescription
=> RF_NewItem_MultiConfigurationProject_Create MultiConfigurationProjectWithDescription

src/test/java/FolderOneTest.java, src/test/java/FreestyleProjectSecondTest.java, src/test/java/model/FreestyleProjectConfigPage.java, src/test/java/model/FreestyleProjectStatusPage.java
https://trello.com/c/UzQRH2LI/940-rf-freestyleprojectsecondtest-refactoring-to-pom
=> RF | FreestyleProjectSecondTest > refactoring to POM

src/test/java/FooterTest.java, src/test/java/model/FooterPage.java, src/test/java/model/HomePage.java, src/test/java/model/XmlPage.java
[RF} - https://trello.com/c/u0HRA00w/928-rf-footertest-testfooterrestapiclickonxmlapidisplayxml
- Refactoring test testFooterRestApiClickOnXmlApiDisplayXML use POM
=> RF| FooterTest > testFooterRestApiClickOnXmlApiDisplayXML

src/test/java/NewView1Test.java, src/test/java/model/EditViewPage.java
Refactor testViewHasSelectedTypeGlobalView() to POM;
Add to model EditViewPage() new @FindBy and method;
[Rf Trello](https://trello.com/c/k6iJGmWj/936-rf-newview1test-testviewhasselectedtypeglobalview)
=> RF | NewView1Test > testViewHasSelectedTypeGlobalView

src/test/java/UserProfileTest.java, src/test/java/model/HomePage.java, src/test/java/model/StatusUserPage.java
test refactored according POM
https://trello.com/c/rJa1tyTn/914-rf-userprofiletest-testuserprofilepreviewdescription-pom
=> RF | UserProfileTest> testUserProfilePreviewDescription POM

src/test/java/UserProfileTest.java, src/test/java/model/StatusUserPage.java
Refactoring testUserProfileHidePreviewDescription
RF - https://trello.com/c/BfQcf7nc/946-rf-userprofiletest-testuserprofilehidepreviewdescriptionpom
=> RF | UserProfileTest> testUserProfileHidePreviewDescriptionPOM

src/test/java/NewItemCreatePipelineTest.java, src/test/java/OrganizationFolderTest.java, src/test/java/model/OrgFolderStatusPage.java
POM refactored renameOrgFolder test
=> Err_ Rename Organization Folder

src/test/java/FreestyleProjectTest.java, src/test/java/model/FreestyleProjectStatusPage.java, src/test/java/model/HomePage.java
https://trello.com/c/LYwQAU9E/943-rf-classname-testname
Created locators for testCreateBuildNowOnFreestyleProjectPage() on FreestyleProjectStatusPage:
buttonOpenBuildHistoryOnSidePanel;
buildRowsOnBuildsInformation;
buttonBuildNowOnSidePanel;
buildLoadingIconSuccess;
Created methods for testCreateBuildNowOnFreestyleProjectPage() on FreestyleProjectStatusPage:
clickBuildNowOnSidePanel()
openBuildHistoryOnSidePanel() 
countBuildsOnSidePanel()
=> RF | Freestyle Project > testCreateBuildNowOnFreestyleProjectPage() in POM

src/test/java/NewView1Test.java
Refactor testViewHasSelectedTypeMyView() to POM;
[RF Trello](https://trello.com/c/C6R7EPtQ/951-rf-newview1test-testviewhasselectedtypemyview)
=> RF | NewView1Test > testViewHasSelectedTypeMyView

src/test/java/HeaderTest.java, src/test/java/model/BuildsUserPage.java, src/test/java/model/HomePage.java
Create model BuildsUserPage;
Refactor testUserDropdownMenuToOpenPageUserBuilds() to POM; 
Add @FindBy and method in BuildsUserPage (getHeaderH1Text()); 
Add @FindBy and method in HomePage (clickBuildsItemInUserDropdownMenu());
[Trello](https://trello.com/c/Eb4lBqRu/952-rf-headertest-user-dropdown-menu-open-page-builds-by-click-on-item-in-user-dropdown-menu)
=> RF | HeaderTest > testUserDropdownMenuToOpenPageUserBuilds

src/test/java/NewView1Test.java, src/test/java/model/ViewPage.java
Refactor testDeleteView() to POM;
Add to model ViewPage locators and methods clickDeleteViewItem(), clickYesButtonDeleteView();
[Trello](https://trello.com/c/1vbrrw2Y/954-rf-newview1test-testdeleteview)
=> RF | NewView1Test > testDeleteView

src/test/java/FolderOneTest.java, src/test/java/model/FolderStatusPage.java
testCreateMultibranchPipelineInFolder modified to be transferred to the POM;
getHeaderFolderText method added to FolderStatusPage.
https://trello.com/c/RkB6Ygow/953-rf-folder-create-multibranch-pipeline-in-folder
=> RF testCreateMultibranchPipelineInFolder

src/test/java/FolderTest.java, src/test/java/model/FolderConfigPage.java, src/test/java/model/HomePage.java
refactoring test testConfigureFolderDisplayName
=> refactoring testConfigureFolderDisplayName

src/test/java/BuildHistoryTest.java
=> RF | BuildHistoryTest > metods

src/test/java/PipelineTest.java, src/test/java/model/PipelineConfigPage.java
refactoring testPipelinePreviewDescription
https://trello.com/c/vaBhZozb/978-rf-pipeline-add-description-preview-description
=> RF | Pipeline > Add description > Preview description

src/test/java/HomeTest.java, src/test/java/model/HomePage.java, src/test/java/model/PipelineConfigPage.java, src/test/java/model/PipelineProjectPage.java
testBuildNewPipeline, HomeTest class, and methods added
AT - https://trello.com/c/PwXhIODR/976-at-020301-new-item-pipeline-create-pipeline-no-build
=> AT 02.03.01 New item_Pipeline_Create Pipeline_No Build

src/test/java/FreestyleProjectTest.java
https://trello.com/c/vEDveBUL/918-rf-freestyleprojecttest-testfreestyleprojectpageisopenedfromdashboard
=> RF | FreestyleProjectTest> testFreestyleProjectPageIsOpenedFromDashboard

src/test/java/PipelineTest.java, src/test/java/model/NewItemPage.java, src/test/java/model/PipelineProjectPage.java
https://trello.com/c/WsyOtsua/902-err-newitemcreatepipelinetest-testcreatenewpipelinefromexisting
=> ERR | NewItemCreatePipelineTest > testCreateNewPipelineFromExisting

src/test/java/MulticonfigurationProjectTest.java, src/test/java/model/HomePage.java, src/test/java/model/MultiConfigurationProjectStatusPage.java, src/test/java/model/MulticonfigurationProjectConfigPage.java, src/test/java/model/NewItemPage.java
Refactoring testCreateNewMCProjectAsCopyFromExistingProject() to POM
https://trello.com/c/c4HoKv2Z/981-rf-multiconfigurationprojecttest-testcreatenewmcprojectascopyfromexistingproject
=> RF | MulticonfigurationProjectTest > testCreateNewMCProjectAsCopyFromExistingProject()

src/test/java/PipelineTest.java, src/test/java/model/HomePage.java
refactor testDeletePipelineFromDashboard() and add dependency
change getHeaderText() waiting from 3 to 5 sec
[RF] - https://trello.com/c/SGRVO18A
=> RF | PipelineTest > testDeletePipelineFromDashboard

src/test/java/FolderTest.java, src/test/java/model/FolderStatusPage.java
[ERR] https://trello.com/c/mJkQhEFi
=> ERR_Folder_Create_Freestyle_project_in_folder(using_crambmenu)

src/test/java/FolderTest.java, src/test/java/model/JobPage.java
refactoring testMoveFolderInFolder
=> RF testMoveFolderInFolder

src/test/java/HomeTest.java, src/test/java/model/HomePage.java, src/test/java/model/PipelineProjectPage.java
Test testBuildNewPipelineSuccess() added
Methodes clickPipeline1, clickBuildNow, clickDashboard, movePointToCheckBox, getStatusBuildText added
according POM
AT 02.03.02 [Pipeline> Build now | Build Success](https://trello.com/c/qatPGfwh/991-at-0000-item-sub-item)
=> AT 02.03.02 Pipeline> Build now | Build Success /POM attempt 2

src/test/java/PipelineTest.java
[REFACTORING] createPipelineProject() method and renamePipelineProject() method
=> RF | PipelineTest > testRenamePipelineWithValidName

src/test/java/FreestyleProjectTest.java
[RF] https://trello.com/c/g7uEgDmf
refactoring testCreateNewFreestyleProjectWithDuplicateName to POM
=> RF | New Item > Freestyle Project > testCreateNewFreestyleProjectWithDuplicateName (POM)

src/test/java/UserProfileTest.java, src/test/java/model/StatusUserPage.java
https://trello.com/c/2Ry9nabV/1005-rf-1501001-user-profile-page-add-description
testUserProfileAddDescription > refactoring to POM
=> RF 15.01.001 | User profile page > Add Description > Test to POM

pom.xml, src/test/java/cucumber/CucumberTest.java, src/test/java/cucumber/FolderPage.java, src/test/java/runner/BaseTest.java, src/test/java/runner/CucumberDriver.java, src/test/resources/cucumber.properties, src/test/resources/cucumber/folder_test.feature
[Trello](https://trello.com/c/o6RhtZF2/1009-f-000001-create-an-environment-for-cucumber)
=> Create Cucumber test environment end test.

src/test/java/PipelineTest.java, src/test/java/model/RenameItemErrorPage.java, src/test/java/model/RenameItemPage.java
[REFACTORING] testRenamePipelineWithoutChangingName
[CREATED] RenameItemErrorMessagePage POM
=> RF | PipelineTest> testRenamePipelineWithoutChangingName

src/test/java/HeaderTest.java, src/test/java/model/HomePage.java, src/test/java/model/MyViewsPage.java
Refactor testUserDropdownMenuToOpenMyViewsPage() to POM;
Add method getMyViewItemNameOnTopBar() to ConfigureUserPage; 
Add method clickMyViewItemInUserDropdownMenu() to HomePage;
[Trello](https://trello.com/c/p1SSOVIt/997-rf-headertest-testuserdropdownmenutoopenmyviewspage)
=> RF | HeaderTest > testUserDropdownMenuToOpenMyViewsPage

src/test/java/HeaderTest.java, src/test/java/model/CredentialsPage.java, src/test/java/model/HomePage.java
Create model CredentialsPage;
Refactor testUserDropdownMenuToOpenCredentialsPage() to POM;
Add method getHeaderH1Text() in CredentialsPage;
Add method clickCredentialsItemInUserDropdownMenu() in HomePage;
Delete method openUserDropdownMenu() from HeaderTest;
[Trello](https://trello.com/c/C94jMHoP/998-rf-headertest-testuserdropdownmenutoopencredentialspage)
=> RF | HeaderTest > testUserDropdownMenuToOpenCredentialsPage

src/test/java/FreestyleProjectTest.java, src/test/java/model/BaseConfigPage.java, src/test/java/model/BaseStatusPage.java, src/test/java/model/FreestyleProjectConfigPage.java, src/test/java/model/FreestyleProjectStatusPage.java, src/test/java/model/HomePage.java
https://trello.com/c/nI5iUlJn/899-rf-freestyleprojecttest-testdisableproject
=> RF | FreestyleProjectTest > testDisableProject

src/test/java/FreestyleProjectTest.java, src/test/java/model/ChangesBuildsPage.java, src/test/java/model/FreestyleProjectStatusPage.java
https://trello.com/c/LIktjgNx/1015-rf-freestyleprojecttest-refactor-to-pom
REF to POM testDisableProject,
testNoBuildFreestyleProjectChanges,
testEditFreestyleProjectWithDescription
Delete duplicated tests
=> REF to POM FreestyleProjectTest

src/test/java/FreestyleProjectSecondTest.java, src/test/java/model/FreestyleProjectConfigPage.java
Refactoring testSelectBuildPeriodicallyCheckbox() to POM
[RF] - https://trello.com/c/KH603tcn
=> RF | FreestyleProjectSecondTest > refactoring testSelectBuildPeriodicallyCheckbox to POM

src/test/java/MulticonfigurationProjectTest.java, src/test/java/model/HomePage.java, src/test/java/model/MultiConfigurationProjectStatusPage.java
Refactored testEnableMultiConfigurationProject to POM.
Removed dependency in previous test.
=> RF_enableMCProject

src/test/java/FolderOneTest.java, src/test/java/MultibranchPipelineTest.java, src/test/java/model/FolderStatusPage.java
Moved to the FolderOneTest class
=> RF | testDeleteMultibranchPipelineFromFolder

src/test/java/FooterTest.java, src/test/java/model/FooterPage.java, src/test/java/model/HomePage.java, src/test/java/model/RestApiPage.java, src/test/java/model/XmlPage.java
[RF] - RF| FooterTest > testFooterRestApiClickOnXmlApiDisplayXMLv2 https://trello.com/c/7Y0u3Tdj/1018-rf-footertest-testfooterrestapiclickonxmlapidisplayxmlv2
-refactoring test add RestApiPage
- FooterPage is abstract
=> RF_FooterTest_testFooterRestApiClickOnXmlApiDisplayXML

src/test/java/FolderOneTest.java, src/test/java/MultibranchPipelineTest.java, src/test/java/model/DeleteMultibranchPipelinePage.java, src/test/java/model/HomePage.java
testDeleteMultibranchPipelineUsingDropDown added
https://trello.com/c/Ujgs9eq4/1020-at-050302-multibranch-pipeline-delete-multibranch-pipeline-using-dropdown
=> AT 05.03.02 | Multibranch pipeline > Delete Multibranch Pipeline using DropDown

src/test/java/MultibranchPipelineTest.java
testCreateMultibranchPipeline refactored to POM
https://trello.com/c/Ng2Cn2OU/1025-rf-multibranchpipeline-testcreatemultibranchpipeline
=> RF | MultibranchPipeline > testCreateMultibranchPipeline

src/test/java/MultibranchPipelineTest.java, src/test/java/model/CreateItemErrorPage.java
testCreateMultibranchPipelineInvalidName refactored to POM
https://trello.com/c/d0ZK7ofD/1026-rf-multibranchpipeline-testcreatemultibranchpipelineinvalidname
=> RF | MultibranchPipeline >testCreateMultibranchPipelineInvalidName

src/test/java/FreestyleProjectTest.java
https://trello.com/c/xqbGaDeg/1028-rf-freestyleprojecttest-refactoring-tests-to-pom-and-delete-duplicate-tests
delete testFreestyleProjectBuild
delete testCreateFreestyleProjectWithInvalidCharBeforeName
delete testAccessProjectConfigurationFromTheProjectPage
=> RF_FreestyleProjectTests to POM

src/test/java/FolderTest.java
https://trello.com/c/WOB5VW4z/1031-rf-foldertest-testname
Refactoring tests in POM:
testMoveFreestyleProjectInFolderUsingDropDownMenu() testCreateFreestyleProjectInFolderCreateJob()
testCreateFreestyleProjectInFolderNewItem()
=> RF | FolderTest in POM

src/test/java/OrganizationFolderTest.java, src/test/java/model/NewItemPage.java
https://trello.com/c/wq3fPuEU/1022-rf-organizationfoldertest-testcreateorgfolder
=> RF | OrganizationFolderTest > testCreateOrgFolderExistName

src/test/java/PipelineTest.java
[REFACTORING] testRenamedPipelineIsDisplayedInMyViews  
createNewViewOfTypeMyView() method
=> RF | PipelineTest > testRenamedPipelineIsDisplayedInMyViews

src/test/java/PipelineTest.java, src/test/java/model/HomePage.java
[REFACTORING] testRenamePipelineUsingSpecialCharacter
=> RF | PipelineTest> testRenamePipelineUsingSpecialCharacter

src/test/java/NewView1Test.java, src/test/java/model/EditViewPage.java, src/test/java/model/ViewPage.java
Add testAddSomeJobsToListView() in NewView1Test (POM);
Add method clickLinkTextAddExistingJob() to ViewPage; 
Add method clickJobForInputToListView(String jobName) to EditViewPage;
[trello](https://trello.com/c/MiaVV7lK/1039-at-110301-new-view-edit-view-add-jobs-to-list-view)
=> AT 11.03.01 | New view > Edit View > Add jobs to List View

src/test/java/MulticonfigurationProjectTest.java, src/test/java/MyViewsTest.java, src/test/java/model/MyViewsPage.java
=> RF_editDescriptionInMyViews

src/test/java/tests/CreatePipelineProjectTest.java
NewItemCreatePipelineTest
testCreatePipelineProject()
refactored to POM
=> RF | NewItemCreatePipelineTest - testCreatePipelineProject() refactoring to POM

src/test/java/cucumber/FolderPage.java, src/test/java/model/NewItemPage.java, src/test/java/model/pipeline/PipelineProjectPage.java, src/test/java/tests/BuildHistoryTest.java, src/test/java/tests/CreatePipelineProjectTest.java, src/test/java/tests/EditViewTest.java, src/test/java/tests/FolderOneTest.java, src/test/java/tests/FolderTest.java, src/test/java/tests/FreestyleProjectSecondTest.java, src/test/java/tests/FreestyleProjectTest.java, src/test/java/tests/ListViewTest.java, src/test/java/tests/MultibranchPipelineTest.java, src/test/java/tests/MulticonfigurationProjectTest.java, src/test/java/tests/NewItemTest.java, src/test/java/tests/NewView1Test.java, src/test/java/tests/NewViewTest.java, src/test/java/tests/OrganizationFolderTest.java, src/test/java/tests/PipelineTest.java, src/test/java/tests/ProjectsInFolderTest.java
rf class projectsinfoldertest
RF -
=> RF_class_ProjectsInFolderTest

src/test/java/model/HomePage.java, src/test/java/model/pipeline/PipelineConfigPage.java, src/test/java/model/pipeline/PipelineProjectPage.java, src/test/java/model/views/MyViewsPage.java, src/test/java/tests/NewView1Test.java, src/test/java/tests/PipelineTest.java
[REFACTORING] PipelineTest class (Partial)
=> [REFACTORING] PipelineTest class (Partial)

src/test/java/model/RenameItemPage.java, src/test/java/model/multiconfiguration/MultiConfigurationProjectStatusPage.java, src/test/java/tests/MulticonfigurationProjectTest.java
[Trello](https://trello.com/c/Xi1IEf7V/1062-rf-multi-configuration-project)
[Trello](https://trello.com/c/69B49mwh/1063-rf-multi-configuration-project-delete-multi-configuration-project)
- Refactor testMultiConfigurationProjectRenameProjectViaDropDowntest to POM
- Refactor MultiConfigurationProjectRenameProjectViaSideMenu to POM
- Add method clickRenameButton to class RenameItemPage
- Add method clickRenameSideMenu to class MultiConfigurationProjectStatusPage
- Refactor testMultiConfigurationProjectDelete to POM
=> RF | Multi-configuration Project

src/test/java/model/HomePage.java, src/test/java/model/folder/FolderConfigPage.java, src/test/java/model/folder/FolderStatusPage.java, src/test/java/tests/FolderOneTest.java, src/test/java/tests/FolderTest.java, src/test/java/tests/ProjectsInFolderTest.java
https://trello.com/c/mYv1UIu1/1068-rf-foldertest
https://trello.com/c/diaRpd1e/828-err-foldertest
**Refactoring tests and added DependsOnMethods:**
testCreateFolder()
testCreateMultiConfigurationProjectInFolder()
testConfigureChangeFolderDisplayName()
testConfigureFolderDisplayNameSaveFolderName()
testConfigureFolderAddDescription()
testMoveFolderInFolder()
testDeleteFolder()
testCreateFolderInFolder()
testAddFolderDescription()
testCreateFreestyleProjectInFolderByNewItemDropDownInCrambMenu
testDeleteFolderUsingDropDown
testCreateFolderWithDescriptionAndJobPipeline - **rename to** testCreateMultibranchPipelineProjectInFolder because this test verifies only creating MultibranchPipelineProject in the folder.
**Deleted duplicate tests:**
testConfigureFolderDisplayNameWithDropdownMenu() …
=> RF | FolderTest

src/test/java/model/RestApiPage.java, src/test/java/model/base/FooterPage.java, src/test/java/tests/FooterTest.java
RF - https://trello.com/c/tSuZe7hf/1061-rf-footertest-refactoring-tests-to-pom
Move to POM
=> RF | FooterTest > testFooterLinkRestRedirectToPage

src/test/java/tests/PipelineTest.java
Add check escape characters &, <, > that are dispayed in error message as:
"<" &lt;
">" &gt;
"&" &amp;
https://trello.com/c/mSOHRG3J/1072-rf-pipelinetest-testrenamepipelineusingspecialcharacter-add
=> RF | PipelineTest> testRenamePipelineUsingSpecialCharacter add & < >

src/test/java/model/HomePage.java, src/test/java/model/RenameItemPage.java, src/test/java/model/multibranch_pipeline/MultibranchPipelineStatusPage.java, src/test/java/tests/MultibranchPipelineTest.java
=> RF MultibranchPipelineTest class POM

src/test/java/model/views/EditViewPage.java, src/test/java/model/views/MyViewsPage.java, src/test/java/tests/NewView1Test.java
Add testDeselectJobsFromListView() in NewView1Test (POM);
Add method getTextContentOnViewMainPanel() to MyViewsPage; 
Refactor EditViewPage;
[Trello](https://trello.com/c/HaHfzATQ/1079-at-110318-new-view-edit-view-deselect-jobs-from-list-view)
=> AT 11.03.18 | New view > Edit View > Deselect jobs from List View

src/test/java/model/HomePage.java, src/test/java/model/NewItemPage.java, src/test/java/model/base/Breadcrumbs.java, src/test/java/model/pipeline/PipelineConfigPage.java, src/test/java/model/pipeline/PipelineStatusPage.java, src/test/java/tests/PipelineTest.java
[REFACTORING] PipelineTest class (Full)
=> RF | PipelineTest> PipelineClass

src/test/java/tests/MulticonfigurationProjectTest.java
[Trello](https://trello.com/c/3hZob9wI/1067-rf-multiconfigurationprojecttest-testmulticonfigurationprojectrenametoinvalidnameviasidemenu)
- Refactor testMultiConfigurationProjectRenameToInvalidNameViaSideMenu to POM
=> RF | MulticonfigurationProjectTest > testMultiConfigurationProjectRenameToInvalidNameViaSideMenu

src/test/java/model/NewItemPage.java, src/test/java/model/freestyle/FreestyleProjectConfigPage.java, src/test/java/tests/CopyItemTest.java
RF | CopyItemTest > refactor in POM
=> RF | CopyItemTest > refactor in POM

src/test/java/model/organization_folder/OrgFolderConfigPage.java, src/test/java/tests/OrganizationFolderTest.java
https://trello.com/c/tMtvODuZ/1064-rf-organizationfoldertest-testorgfolderemptyname
=> RF | OrganizationFolderTest > testOrgFolderEmptyName

src/test/java/model/views/MyViewsPage.java, src/test/java/tests/NewView1Test.java
Add testCreateViewWithExistingName() in NewView1Test (POM);
Add method getErrorMessageViewAlreadyExist() in MyViewsPage;
[Trello](https://trello.com/c/LgUKx4NT/1081-at-110106-new-view-create-new-view-test-to-create-view-with-existing-name)
=> AT 11.01.06 | New view > Create new view > Test to create view with existing name

src/test/java/model/BuildStatusPage.java, src/test/java/model/BuildWithParametersPage.java
Rename StatusPage to BuildStatusPage
=> RF | PipelineTest> testBuildParametrizedProject

src/test/java/model/BuildHistoryPage.java, src/test/java/tests/BuildHistoryTest.java
Refactored BuildHistoryTest & BuildHistoryPage
=> RF | BuildHistoryTest > refactor POM

src/test/java/model/NewItemPage.java, src/test/java/tests/NewItemTest.java
- added DataProvider method getTypeProjectList() to testCreateAnyItemWithSpacesOnlyNameError
- deleted method setItemAndClickOk(int index) from NewItemPage
=> RF | NewItemTest > testCreateAnyItemWithSpacesOnlyNameError()

src/test/java/model/BuildHistoryPage.java, src/test/java/tests/BuildHistoryTest.java
[RF][POM]-https://trello.com/c/uZoGqGY3/986-rf-buildhistorytest-refactor-pom
=> RF_BuildHistoryTest_refactor_POM

src/test/java/model/BuildHistoryPage.java, src/test/java/tests/BuildHistoryTest.java
RF | BuildHistory > Delete tests
RF - https://trello.com/c/6uR18XNX/1103-rf-buildhistory-h1headertest
=> Deleted tests and RF asserts

src/test/java/model/BuildHistoryPage.java, src/test/java/tests/BuildHistoryTest.java
RF -  https://trello.com/c/3EIUAfBs/1104-rf-buildhistorytest-test-public-void-testiftheiconlegendexist
in the Test IfTheIconlegentExist changed the Assert
=> RfIfTheIconLegendExist

src/test/java/runner/BaseTest.java, src/test/java/runner/CucumberDriver.java, src/test/java/runner/JenkinsUtils.java
Delete static method from baseutil
[Trello](https://trello.com/c/f9bJU3QZ/1099-rf-runner-besetest)
=> Refactor BaseUtil

src/test/java/model/multiconfiguration/MultiConfigurationProjectStatusPage.java, src/test/java/tests/MulticonfigurationProjectTest.java
https://trello.com/c/O83Ms4Lf
testMultiConfigurationProjectEnableCheckIconProjectName to POM
add method iconProjectEnabledIsDisplayed to MultiConfigurationProjectStatusPage
=> RF | MulticonfigurationProjectTest > testMultiConfigurationProjectEnableCheckIconProjectName

src/test/java/model/MovePage.java, src/test/java/model/folder/FolderStatusPage.java, src/test/java/tests/EditViewTest.java, src/test/java/tests/FreestyleProjectTest.java, src/test/java/tests/MulticonfigurationProjectTest.java, src/test/java/tests/OrganizationFolderTest.java
https://trello.com/c/Lk8Q0xY0/1050-rf-organizationfoldertest-testmoveorgfoldertodashboard
=> RF | OrganizationFolderTest> testMoveOrgFolderToDashboard

src/test/java/model/multiconfiguration/MultiConfigurationProjectConfigPage.java, src/test/java/model/multiconfiguration/MultiConfigurationProjectStatusPage.java, src/test/java/tests/MulticonfigurationProjectTest.java
[Trello](https://trello.com/c/Gw0l5Nkx/1116-rf-multiconfiguration-project-configure-disable-project)
-Refactor testMultiConfigurationProjectDisable to POM
-Add new method to MultiConfigurationProjectConfigPage
-Add new method to MultiConfigurationProjectStatusPage
-Change dependencies due to conflicts within the class
=> RF | MulticonfigurationProjectTest> testMultiConfigurationProjectDisable

src/test/java/model/multiconfiguration/MultiConfigurationProjectConfigPage.java, src/test/java/model/multiconfiguration/MultiConfigurationProjectStatusPage.java, src/test/java/tests/MulticonfigurationProjectTest.java
[Trello](https://trello.com/c/muf1eHs9/1115-rf-multiconfigurationprojecttest-testmulticonfigurationprojectdisable)
-Refactor testMultiConfigurationProjectEnable to POM
-Add new method to MultiConfigurationProjectStatusPage
=> RF | MulticonfigurationProjectTest > testMultiConfigurationProjectEnable

src/test/java/model/base/Header.java, src/test/java/tests/HeaderTest.java
RF - https://trello.com/c/Zdv5Nm6t
=> RF | HeaderTest > refactoring testSeeNameIcon() and testReturnFromNewItemPageToHomePageByClickingOnHeadIcon() to POM

src/test/java/model/HomePage.java, src/test/java/tests/MulticonfigurationProjectTest.java
[Trello](https://trello.com/c/GApWIR6o/1119-rf-class-test)
-Delete deleteNewMCProject method according to POM
-Delete @ignore and change dependency for testMultiConfigurationProjectBuild
-Delete @ignore and change dependency for  testCreateNewMCProjectAsCopyFromExistingProject
-Delete testCreateMultiConfigurationProjectDisabled duplicate of testMultiConfigurationProjectDisable
-Refactor testFindMultiConfigurationProject to POM
-Add new method setSearchAndClickEnter to HomePage
=> RF | MulticonfigurationProjectTest> testCreateMultiConfigurationProjectDisabled , testFindMultiConfigurationProject

src/test/java/model/ExternalJenkinsPage.java, src/test/java/model/ManageJenkinsPage.java, src/test/java/model/base/Footer.java, src/test/java/tests/FooterTest.java
RF - https://trello.com/c/omG9U7mZ/1117-rf-footertest-testsmovetopom
-Deleted duplicate tests.
-Modified test testFooterLinkJenkinsIsClickable()
-Move all class to POM.
-Footer changed extends from BasePage. Before Footer extends from Header.
=> RF | FooterTest > Tests_move_to_POM

src/test/java/model/HomePage.java, src/test/java/model/freestyle/FreestyleProjectConfigPage.java, src/test/java/model/freestyle/FreestyleProjectStatusPage.java, src/test/java/tests/FreestyleProjectTest.java
ERR | FreestyleProjectTest> testAddDaysToKeepBuildsInConfigure.
- Delete `@Ignore` testAddDaysToKeepBuildsInConfigure();
- Add waits and scrolls for stabilizing flaky-tests in class FreestyleProjectTest;
- Add `@Ignore` [testConfigureSourceCodeByGIT()](https://trello.com/c/FVFiTduE/1122-err-freestyleprojecttest-testconfiguresourcecodebygit).
=> ERR | FreestyleProjectTest> testAddDaysToKeepBuildsInConfigure

src/test/java/model/GlobalToolConfigurationPage.java, src/test/java/model/pipeline/PipelineStatusPage.java, src/test/java/tests/FolderTest.java, src/test/java/tests/PipelineTest.java
ERR | PipelineTest > testEditPipelineDescription (Trello has 3 ERR-cards with this problem).
- Add ignore [ERR | FolderTest > testDeleteFreestyleProjectInFolder](https://trello.com/c/pXGXXfi6/1094-err-foldertest-testdeletefreestyleprojectinfolder)
- Add waits/scrolls and refactor for stabilizing flaky-tests `testEditPipelineDescription()` and `testWarningMessageIsDisappeared()` in class PipelineTest.
=> ERR | PipelineTest > testEditPipelineDescription

src/test/java/model/base/BaseStatusPage.java
Fix flaky-test `testAddDescription()` (early named `testAddingDescription()`)
=> ERR | FreestyleProjectTest > testAddDescription

src/test/java/model/RenameItemPage.java, src/test/java/model/base/BaseStatusPage.java, src/test/java/tests/MultibranchPipelineTest.java
ERR MultibranchPipelineTest:
- renamed testRenameMultiBranchPipelineFrom_Dropdown() to testRenameMultiBranchPipelineFromDropdown();
- added waits for stabilization of flaky-test.
=> ERR | MultibranchPipelineTest

src/test/java/model/GlobalToolConfigurationPage.java, src/test/java/model/HomePage.java, src/test/java/model/multiconfiguration/MultiConfigurationProjectStatusPage.java
ERR | MulticonfigurationProjectTest > testMultiConfigurationProjectDelete()
- Add wait for stabilization flaky-test testMultiConfigurationProjectDelete()
- Fix error in testWarningMessageIsDisappeared()
=> ERR | MulticonfigurationProjectTest > testMultiConfigurationProjectDelete()

src/test/java/model/folder/FolderStatusPage.java, src/test/java/tests/FolderTest.java
ERR | FolderTest > testDeleteFreestyleProjectInFolder:
Fix error.
=> ERR | FolderTest > testDeleteFreestyleProjectInFolder

src/test/java/model/GlobalToolConfigurationPage.java, src/test/java/model/StatusUserPage.java, src/test/java/tests/UserProfileTest.java
Refactor `UserProfileTest`:
- delete not used imports;
- reformat code;
- rename method `inputTextInDescriptionField()` to `setDescriptionField()`;
- rename variables like `actualResult ` to `actualUserDescription`.
Fix ERR in testWarningMessageIsDisappeared() because CI crashed.
=> RF | UserProfileTest

src/test/java/model/BuildHistoryPage.java, src/test/java/tests/MulticonfigurationProjectTest.java
https://trello.com/c/xRJvmuDS/1107-rf-multiconfigurationprojecttest-testmulticonfigurationprojectsrunjobinbuildhistory
=> RF | MultiConfigurationProjectTest > testMultiConfigurationProjectsRunJobInBuildHistory

src/test/java/model/BuildHistoryPage.java, src/test/java/tests/BuildHistoryTest.java, src/test/java/tests/PipelineTest.java
AT - https://trello.com/c/KvMfhR9o/1128-rf-buildhistorytest-testrssitemsexist
=> RF | BuildHistoryTest > testRssItemsExist

src/test/java/model/base/Header.java, src/test/java/tests/HeaderTest.java
Header: creation isJenkinsHeadIconDisplayed, isJenkinsHeadIconEnabled; deletion getJenkinsNameIcon.
RF - https://trello.com/c/rwZHLUoX/1134-rf-headertest-testlogoheadiconisseen
=> RF_HeaderTest_testLogoHeadIconIsSeen

src/test/java/model/HomePage.java, src/test/java/tests/MulticonfigurationProjectTest.java
add method isDisplayedIconProjectDisabled at HomePage
testMultiConfigurationProjectDisableCheckIconDashboardPage to POM
https://trello.com/c/HWinq4le
=> RF | MulticonfigurationProjectTest > testMultiConfigurationProjectDisableCheckIconDashboardPage

src/test/java/model/HomePage.java, src/test/java/tests/MulticonfigurationProjectTest.java
delete Ignore
Change depends
testMultiConfigurationProjectEnableCheckIconProjectName to POM 
add method isDisplayedIconProjectEnabled at HomePage
https://trello.com/c/Ut4yCKeT
=> RF | MulticonfigurationProjectTest > testEnableMultiConfigurationProjectCheckIconDashboardPage

src/test/java/tests/MulticonfigurationProjectTest.java
Removing duplicate tests:
testCreateMultiConfigurationProjectDisabled
testMultiConfigurationProjectConfigureParams
deleting unused fields
https://trello.com/c/O6A1iHzO
https://trello.com/c/RcW6uFTS
=> ERR | MulticonfigurationProjectTest > testCreateMultiConfigurationProjectDisabled

src/test/java/model/HomePage.java, src/test/java/model/base/Header.java, src/test/java/tests/HeaderTest.java
Deletion of methods: getJenkinsHeadIcon, getDescriptionTextare, getAddDescriptionButton. Creation of methods: isDescriptionTextareaEnabled, isAddDescriptionButtonEnabled
RF - https://trello.com/c/key8xcYS/1136-rf-headertest-testlogoheadiconreloadmainpage
=> RF_HeaderTest_testLogoHeadIconReloadMainPage

src/test/java/cucumber/FolderPage.java, src/test/java/model/base/BaseConfigPage.java, src/test/java/model/freestyle/FreestyleProjectConfigPage.java, src/test/java/model/pipeline/PipelineConfigPage.java, src/test/java/tests/BuildHistoryTest.java, src/test/java/tests/CopyItemTest.java, src/test/java/tests/CreatePipelineProjectTest.java, src/test/java/tests/FolderOneTest.java, src/test/java/tests/FolderTest.java, src/test/java/tests/FreestyleProjectTest.java, src/test/java/tests/HeaderTest.java, src/test/java/tests/ListViewTest.java, src/test/java/tests/MultibranchPipelineTest.java, src/test/java/tests/MulticonfigurationProjectTest.java, src/test/java/tests/NewViewTest.java, src/test/java/tests/OrganizationFolderTest.java, src/test/java/tests/PipelineTest.java, src/test/java/tests/ProjectsInFolderTest.java
https://trello.com/c/cTVxWBJA/1126-rf-baseconfigpage-clicksavebtn
Добавила "_" в названии метода clickSaveButton() класса FreestyleProjectConfigPage, потому что он переопределяет базовый метод  (временное решение, не стала разбираться зачем нам нужен этот BuildWithParametersPage, наследуется от FreestyleProjectStatusPage, может стоит перенести все методы во FreestyleProjectStatusPage).
=> RF | BaseConfigPage> clickSaveBtn

src/test/java/tests/OrganizationFolderTest.java
https://trello.com/c/3MKHjJQr/1139-rf-organizationfoldertest-organizationfoldertest-ref
=> RF | OrganizationFolderTest> OrganizationFolderTest ref

src/test/java/model/HomePage.java, src/test/java/model/views/EditListViewPage.java, src/test/java/model/views/MyViewsPage.java, src/test/java/model/views/ViewPage.java, src/test/java/tests/ListViewTest.java
AT - https://trello.com/c/ag90kRkp
Created methods:
- getNamesAllColumns on the EditListViewPage
- removeSomeColumns on the EditListViewPage
- getJobTableHeadersSize on the HomePage
- override method clickEditViewLink() on the ViewPage
Move listJobTableHeaders locator from MyViewsPage to HomePage
=> AT 11.03.19 | New View > Edit View > Change the number of columns in the ListView

src/test/java/model/base/BaseConfigPage.java, src/test/java/model/folder/FolderConfigPage.java, src/test/java/model/freestyle/FreestyleProjectConfigPage.java, src/test/java/model/multibranch_pipeline/MultibranchPipelineConfigPage.java, src/test/java/model/multiconfiguration/MultiConfigurationProjectConfigPage.java, src/test/java/model/organization_folder/OrgFolderConfigPage.java, src/test/java/model/pipeline/PipelineConfigPage.java
https://trello.com/c/VZKeGk7y/1138-rf-folderconfigpage-clickapplybutton
- clickApplyButton() вынесен в BaseConfigPage, теперь доступен для всех конфигурационных страниц, возвращает текущую конфигурационную страницу
=> RF | FolderConfigPage> clickApplyButton

src/test/java/model/ExternalJenkinsPage.java, src/test/java/model/HomePage.java, src/test/java/model/ManageJenkinsPage.java, src/test/java/model/PeoplePage.java, src/test/java/model/RestApiPage.java, src/test/java/model/base/BreadcrumbsComponent.java, src/test/java/model/base/FooterComponent.java, src/test/java/model/base/HeaderComponent.java, src/test/java/tests/FooterComponentTest.java, src/test/java/tests/HeaderComponentTest.java
Refactoring of Header to HederComponents
Refactoring of Footer to FooterComponents
Refactoring of Bredcrumbs to BredcrumbsComponents
=> RF | Renaiming of class Header, Footer, Breadcrumbs

src/test/java/tests/FreestyleProjectTest.java
=> ERR | FreestyleProjectTest> testAddMaxNumberOfBuildsToKeepInConfigure

src/test/java/model/pipeline/PipelineStatusPage.java, src/test/java/tests/FooterComponentTest.java, src/test/java/tests/PipelineTest.java
ERR | PipelineTest > testDeletePipelineFromDashboard
=> ERR | PipelineTest > testDeletePipelineFromDashboard

src/test/java/model/freestyle/FreestyleProjectConfigPage.java, src/test/java/tests/FreestyleProjectTest.java
Fix ERR | FreestyleProjectTest> testBuildStepsOptions
=> ERR | FreestyleProjectTest> testBuildStepsOptions

src/test/java/model/CreateUserPage.java, src/test/java/tests/ManageJenkinsTest.java
testCreateUserWithEmptyName() added
[AT] - https://trello.com/c/ghcfRuRv
=> AT 07.01.08 | People > People > Create User With Empty Name

src/test/java/model/BuildHistoryPage.java, src/test/java/model/BuildWithParametersPage.java, src/test/java/model/HomePage.java, src/test/java/model/ManageOldDataPage.java, src/test/java/model/ManageUsersPage.java, src/test/java/model/MovePage.java, src/test/java/model/NewItemPage.java, src/test/java/model/RenameItemErrorPage.java, src/test/java/model/RestApiPage.java, src/test/java/model/StatusUserPage.java, src/test/java/model/UpdateCenterPage.java, src/test/java/model/XmlPage.java, src/test/java/model/folder/FolderStatusPage.java, src/test/java/model/freestyle/FreestyleProjectConfigPage.java, src/test/java/model/freestyle/FreestyleProjectStatusPage.java, src/test/java/model/multiconfiguration/MultiConfigurationProjectConfigPage.java, src/test/java/model/multiconfiguration/MultiConfigurationProjectStatusPage.java, src/test/java/runner/BaseUtils.java, src/test/java/runner/JenkinsUtils.java, src/test/java/runner/ProjectUtils.java
Delation of unused imports, elements and metods
RF - https://trello.com/c/cc1ZzX1M/1157-rf-delation-of-unused-imports-elements-and-metods
=> RF_Delation_of_unused_imports,_elements_and_metods

src/test/java/model/DeletePage.java, src/test/java/model/HomePage.java, src/test/java/model/ManageUsersPage.java, src/test/java/model/folder/FolderStatusPage.java, src/test/java/model/multibranch_pipeline/MultibranchPipelineStatusPage.java, src/test/java/model/views/ViewPage.java, src/test/java/tests/CreateUserTest.java, src/test/java/tests/FolderOneTest.java, src/test/java/tests/FolderTest.java, src/test/java/tests/ListViewTest.java, src/test/java/tests/NewViewTest.java, src/test/java/tests/PeoplePageTest.java
class DeletePage:
- added method clickYes()
- added ParentPage generic
class MultibranchPipelineStatusPage:
- added methods clickDeleteMultibranchPipelineWithOutFolder() , clickDeleteMultibranchPipelineWithFolder()
=> RF | DeletePage> add clickYes method

src/test/java/model/base/BasePageWithSideMenu.java, src/test/java/runner/ProjectMethodsUtils.java, src/test/java/tests/FreestyleProjectTest.java, src/test/java/tests/MulticonfigurationProjectTest.java, src/test/java/tests/PipelineTest.java
[CREATED] ProjectMethodsUtils class
- RF PipelineTest class
=> RF | Created Project Method Utils

src/test/java/cucumber/FolderPage.java, src/test/java/cucumber/MultiBranchPipelinePage.java, src/test/java/model/base/BasePage.java, src/test/java/model/base/BreadcrumbsComponent.java, src/test/java/model/freestyle/FreestyleProjectStatusPage.java, src/test/java/runner/BaseModel.java, src/test/java/tests/BuildHistoryTest.java, src/test/java/tests/CopyItemTest.java, src/test/java/tests/EditViewTest.java, src/test/java/tests/FolderOneTest.java, src/test/java/tests/FolderTest.java, src/test/java/tests/FreestyleProjectTest.java, src/test/java/tests/HeaderComponentTest.java, src/test/java/tests/ListViewTest.java, src/test/java/tests/MultibranchPipelineTest.java, src/test/java/tests/MulticonfigurationProjectTest.java, src/test/java/tests/NewItemTest.java, src/test/java/tests/NewViewTest.java, src/test/java/tests/OrganizationFolderTest.java, src/test/java/tests/PipelineTest.java, src/test/java/tests/ProjectsInFolderTest.java
Moved param and methods to BreadscrimbComponents, removed duplicate
Moved getCurrentUrl() to BaseModel
Ref clickDashboard() in tests
=> Ref | BasePage

src/test/java/model/NewItemPage.java, src/test/java/tests/NewItemTest.java
https://trello.com/c/eyaHcdGe
RenametestCreateNewItemWithEmptyName to testCreateNewItemTypePipelineWithEmptyName
Deleted dependsy in testCreateNewItemFromOtherNonExistingName
Refactor setItem in class NewItemPage
=> RF_NewItemTest

src/test/java/tests/PipelineTest.java
[RF] - https://trello.com/c/ue5pjkYJ
change dependency of testEnablePipelineProject() from testCreatePipelineWithName to testDisablePipelineProjectMessage
refactor testEnablePipelineProject()
=> RF | PipelineTest > testEnablePipelineProject
